import '../../animated_call.dart';
import 'all_4_all_8.dart';
import 'box_counter_rotate.dart';
import 'box_transfer.dart';
import 'checkmate.dart';
import 'hourglass_circulate.dart';
import 'diamond_chain_thru.dart';
import 'remake.dart';
import 'in_roll_circulate.dart';
import 'mini_busy.dart';
import 'motivate.dart';
import 'pass_and_roll.dart';
import 'pass_and_roll_your_neighbor.dart';
import 'peel_and_trail.dart';
import 'recycle.dart';
import 'scoot_and_weave.dart';
import 'scoot_chain_thru.dart';
import 'single_wheel.dart';
import 'slip.dart';
import 'spin_the_windmill.dart';
import 'swing_and_mix.dart';
import 'switch_the_wave.dart';
import 'switch_to_a_diamond.dart';
import 'trade_circulate.dart';
import 'trail_off.dart';
import 'transfer_and_anything.dart';
import 'zig_and_zag.dart';
class CallsIndex {
  static Map<String,List<AnimatedCall>> index = {
      'All8Recycle' : [ All4All8[53],All4All8[54],Recycle[8] ],
      'All4CouplesChaseRight' : [ All4All8[0] ],
      'All4CouplesFantheTop' : [ All4All8[1] ],
      'All4CouplesLeftChase' : [ All4All8[2] ],
      'All4CouplesLeftTouch14' : [ All4All8[3] ],
      'All4CouplesPassThru' : [ All4All8[4] ],
      'All4CouplesPasstheOcean' : [ All4All8[5] ],
      'All4CouplesRightandLeftThru' : [ All4All8[6] ],
      'All4CouplesSingleCircletoaWave' : [ All4All8[7] ],
      'All4CouplesSlideThru' : [ All4All8[8],All4All8[9],All4All8[10] ],
      'All4CouplesSpintheTop' : [ All4All8[11] ],
      'All4CouplesSquareThru' : [ All4All8[12] ],
      'All4CouplesSquareThrutoaWave' : [ All4All8[13] ],
      'All4CouplesSquareThru3' : [ All4All8[14] ],
      'All4CouplesSquareThru3toaWave' : [ All4All8[15] ],
      'All4CouplesSquareThru2' : [ All4All8[16] ],
      'All4CouplesSquareThru2toaWave' : [ All4All8[17] ],
      'All4CouplesStarThru' : [ All4All8[18],All4All8[19],All4All8[20] ],
      'All4CouplesSteptoaWave' : [ All4All8[21] ],
      'All4CouplesSwingThru' : [ All4All8[22] ],
      'All4CouplesTouch14' : [ All4All8[23] ],
      'All4CouplesTurnThru' : [ All4All8[24] ],
      'All8BoxCirculate' : [ All4All8[25],All4All8[26] ],
      'All8ChainDowntheLine' : [ All4All8[27],All4All8[28] ],
      'All8ChaseRight' : [ All4All8[29] ],
      'All8LeftChase' : [ All4All8[30] ],
      'All8Crossfire' : [ All4All8[31],All4All8[32] ],
      'All8CuttheDiamond' : [ All4All8[33] ],
      'All8DiamondCirculate' : [ All4All8[34],All4All8[35],All4All8[36],All4All8[37] ],
      'All8DixieStyletoaWave' : [ All4All8[38],All4All8[40] ],
      'All8ReverseDixieStyletoaWave' : [ All4All8[39],All4All8[41] ],
      'All8ExplodetheWave' : [ All4All8[42] ],
      'All8FliptheDiamond' : [ All4All8[43] ],
      'All8Flutterwheel' : [ All4All8[44] ],
      'All8FollowYourNeighbor' : [ All4All8[45] ],
      'All8FollowYourNeighborandSpread' : [ All4All8[46] ],
      'All812Tag' : [ All4All8[47] ],
      'All8LeftSwingThru' : [ All4All8[48] ],
      'All8LinearCycle' : [ All4All8[49] ],
      'All8PeelOff' : [ All4All8[50] ],
      'All8PeeltheTop' : [ All4All8[51],All4All8[52] ],
      'All8ReverseFlutterwheel' : [ All4All8[56] ],
      'All8ScootBack' : [ All4All8[57] ],
      'All8SwingThru' : [ All4All8[58] ],
      'All8VeerLeft' : [ All4All8[59] ],
      'All8WalkandDodge' : [ All4All8[60] ],
      'All8Zoom' : [ All4All8[61] ],
      'All4CouplesBraceThru' : [ All4All8[62] ],
      'All4CouplesCrossTrailThru' : [ All4All8[63] ],
      'All4CouplesDoubleStarThru' : [ All4All8[64] ],
      'All4CouplesPairOff' : [ All4All8[65] ],
      'All4CouplesPassIn' : [ All4All8[66] ],
      'All4CouplesPassOut' : [ All4All8[67] ],
      'All4CouplesPasstheSea' : [ All4All8[68] ],
      'All4Couples14In' : [ All4All8[69] ],
      'All4Couples14Out' : [ All4All8[70] ],
      'All4CouplesSquareChainThru' : [ All4All8[71] ],
      'All8Left14Thru' : [ All4All8[72] ],
      'All8LeftRolltoaWave' : [ All4All8[73],All4All8[74],All4All8[75] ],
      'All8LeftWheelThru' : [ All4All8[76] ],
      'All8Lockit' : [ All4All8[77],All4All8[78] ],
      'All8Mix' : [ All4All8[79],All4All8[80] ],
      'All8PartnerTag' : [ All4All8[81] ],
      'All814Thru' : [ All4All8[82] ],
      'All8ReverseSwap' : [ All4All8[83] ],
      'All8RightRolltoaWave' : [ All4All8[84],All4All8[85],All4All8[86] ],
      'All8ScootandDodge' : [ All4All8[87],All4All8[88] ],
      'All8Swap' : [ All4All8[89] ],
      'All834Thru' : [ All4All8[90] ],
      'All8TurnandDeal' : [ All4All8[91],All4All8[92],All4All8[93],All4All8[94] ],
      'All8WheelThru' : [ All4All8[95] ],
      'AsCouplesRecycle' : [ Recycle[6] ],
      'BoxCounterRotate' : [ BoxCounterRotate[0],BoxCounterRotate[1],BoxCounterRotate[2],BoxCounterRotate[3],BoxCounterRotate[4],BoxCounterRotate[5],BoxCounterRotate[6],BoxCounterRotate[7],BoxCounterRotate[8],BoxCounterRotate[9],BoxCounterRotate[10],BoxCounterRotate[11],BoxCounterRotate[12],BoxCounterRotate[13],BoxCounterRotate[14],BoxCounterRotate[15],BoxCounterRotate[16],BoxCounterRotate[17],BoxCounterRotate[18],BoxCounterRotate[19],BoxCounterRotate[20],BoxCounterRotate[21],BoxCounterRotate[0],BoxCounterRotate[1],BoxCounterRotate[2],BoxCounterRotate[3],BoxCounterRotate[4],BoxCounterRotate[5],BoxCounterRotate[6],BoxCounterRotate[7],BoxCounterRotate[8],BoxCounterRotate[9],BoxCounterRotate[10],BoxCounterRotate[11],BoxCounterRotate[12],BoxCounterRotate[13],BoxCounterRotate[14],BoxCounterRotate[15],BoxCounterRotate[16],BoxCounterRotate[17],BoxCounterRotate[18],BoxCounterRotate[19],BoxCounterRotate[20],BoxCounterRotate[21] ],
      'BoxCounterRotate34' : [ BoxCounterRotate[22],BoxCounterRotate[22] ],
      'AsCouplesBoxCounterRotate' : [ BoxCounterRotate[23],BoxCounterRotate[23] ],
      'SplitCounterRotate' : [ BoxCounterRotate[24],BoxCounterRotate[25],BoxCounterRotate[26],BoxCounterRotate[27],BoxCounterRotate[28],BoxCounterRotate[29],BoxCounterRotate[30],BoxCounterRotate[31],BoxCounterRotate[32],BoxCounterRotate[33],BoxCounterRotate[34],BoxCounterRotate[35],BoxCounterRotate[36],BoxCounterRotate[37],BoxCounterRotate[38],BoxCounterRotate[24],BoxCounterRotate[25],BoxCounterRotate[26],BoxCounterRotate[27],BoxCounterRotate[28],BoxCounterRotate[29],BoxCounterRotate[30],BoxCounterRotate[31],BoxCounterRotate[32],BoxCounterRotate[33],BoxCounterRotate[34],BoxCounterRotate[35],BoxCounterRotate[36],BoxCounterRotate[37],BoxCounterRotate[38] ],
      'BoxTransfer' : [ BoxTransfer[0],BoxTransfer[1],BoxTransfer[0],BoxTransfer[1] ],
      'All8BoxTransfer' : [ BoxTransfer[2],BoxTransfer[2] ],
      'AsCouplesBoxTransfer' : [ BoxTransfer[3],BoxTransfer[3] ],
      'SplitTransfer' : [ BoxTransfer[4],BoxTransfer[5],BoxTransfer[6],BoxTransfer[7],BoxTransfer[4],BoxTransfer[5],BoxTransfer[6],BoxTransfer[7] ],
      'Checkmate' : [ Checkmate[0],Checkmate[1],Checkmate[2],Checkmate[3] ],
      'HourglassCirculate' : [ HourglassCirculate[0],HourglassCirculate[1],HourglassCirculate[2],HourglassCirculate[3],HourglassCirculate[0],HourglassCirculate[1],HourglassCirculate[2],HourglassCirculate[3],HourglassCirculate[0],HourglassCirculate[1],HourglassCirculate[2],HourglassCirculate[3] ],
      'BigHourglassCirculate' : [ HourglassCirculate[4],HourglassCirculate[5],HourglassCirculate[4],HourglassCirculate[5],HourglassCirculate[4],HourglassCirculate[5] ],
      'CuttheHourglass' : [ HourglassCirculate[6],HourglassCirculate[7],HourglassCirculate[8],HourglassCirculate[9],HourglassCirculate[10],HourglassCirculate[11],HourglassCirculate[12],HourglassCirculate[13],HourglassCirculate[6],HourglassCirculate[7],HourglassCirculate[8],HourglassCirculate[9],HourglassCirculate[10],HourglassCirculate[11],HourglassCirculate[12],HourglassCirculate[13],HourglassCirculate[6],HourglassCirculate[7],HourglassCirculate[8],HourglassCirculate[9],HourglassCirculate[10],HourglassCirculate[11],HourglassCirculate[12],HourglassCirculate[13] ],
      'FliptheHourglass' : [ HourglassCirculate[14],HourglassCirculate[15],HourglassCirculate[16],HourglassCirculate[17],HourglassCirculate[18],HourglassCirculate[19],HourglassCirculate[20],HourglassCirculate[21],HourglassCirculate[14],HourglassCirculate[15],HourglassCirculate[16],HourglassCirculate[17],HourglassCirculate[18],HourglassCirculate[19],HourglassCirculate[20],HourglassCirculate[21],HourglassCirculate[14],HourglassCirculate[15],HourglassCirculate[16],HourglassCirculate[17],HourglassCirculate[18],HourglassCirculate[19],HourglassCirculate[20],HourglassCirculate[21] ],
      'FliptheHourglassandRoll' : [ HourglassCirculate[22],HourglassCirculate[22],HourglassCirculate[22] ],
      'DiamondChainThru' : [ DiamondChainThru[0],DiamondChainThru[1],DiamondChainThru[2],DiamondChainThru[3] ],
      'Remake' : [ Remake[0],Remake[1],Remake[2],Remake[3],Remake[4],Remake[0],Remake[1],Remake[2],Remake[3],Remake[4],Remake[0],Remake[1],Remake[2],Remake[3],Remake[4] ],
      'LeftRemake' : [ Remake[5],Remake[6],Remake[7],Remake[8],Remake[9],Remake[5],Remake[6],Remake[7],Remake[8],Remake[9],Remake[5],Remake[6],Remake[7],Remake[8],Remake[9] ],
      'AnyHandRemake' : [ Remake[10],Remake[11],Remake[12],Remake[13],Remake[14],Remake[15],Remake[10],Remake[11],Remake[12],Remake[13],Remake[14],Remake[15],Remake[10],Remake[11],Remake[12],Remake[13],Remake[14],Remake[15] ],
      'RemaketheAlamo' : [ Remake[16],Remake[16],Remake[16] ],
      'All8Remake' : [ Remake[17],Remake[17],Remake[17] ],
      'All8LeftRemake' : [ Remake[18],Remake[18],Remake[18] ],
      'AsCouplesRemake' : [ Remake[19],Remake[19],Remake[19] ],
      'GrandRemake' : [ Remake[20],Remake[20],Remake[20] ],
      'LeftGrandRemake' : [ Remake[21],Remake[21],Remake[21] ],
      'RemaketheThar' : [ Remake[22],Remake[23],Remake[22],Remake[23],Remake[22],Remake[23] ],
      'InRollCirculate' : [ InRollCirculate[0],InRollCirculate[1],InRollCirculate[2],InRollCirculate[3],InRollCirculate[4],InRollCirculate[5],InRollCirculate[6],InRollCirculate[7],InRollCirculate[0],InRollCirculate[1],InRollCirculate[2],InRollCirculate[3],InRollCirculate[4],InRollCirculate[5],InRollCirculate[6],InRollCirculate[7] ],
      'OutRollCirculate' : [ InRollCirculate[8],InRollCirculate[9],InRollCirculate[10],InRollCirculate[11],InRollCirculate[12],InRollCirculate[13],InRollCirculate[14],InRollCirculate[15],InRollCirculate[8],InRollCirculate[9],InRollCirculate[10],InRollCirculate[11],InRollCirculate[12],InRollCirculate[13],InRollCirculate[14],InRollCirculate[15] ],
      'MiniBusy' : [ MiniBusy[0],MiniBusy[2] ],
      '_miniBusyBut' : [ MiniBusy[1],MiniBusy[3] ],
      '23MiniBusy' : [ MiniBusy[4],MiniBusy[5] ],
      'Motivate' : [ Motivate[0],Motivate[1],Motivate[2],Motivate[3] ],
      'MotivateTurntheStar14' : [ Motivate[4],Motivate[5] ],
      'MotivateTurntheStar34' : [ Motivate[6],Motivate[7] ],
      'MotivateDoNotTurntheStar' : [ Motivate[8],Motivate[9] ],
      'PassandRoll' : [ PassAndRoll[0],PassAndRoll[1],PassAndRoll[2],PassAndRoll[3] ],
      'LeftPassandRoll' : [ PassAndRoll[4],PassAndRoll[5],PassAndRoll[6],PassAndRoll[7] ],
      'All8PassandRoll' : [ PassAndRoll[8] ],
      'AsCouplesPassandRoll' : [ PassAndRoll[9] ],
      'PassandRollYourNeighbor' : [ PassAndRollYourNeighbor[0],PassAndRollYourNeighbor[1],PassAndRollYourNeighbor[2],PassAndRollYourNeighbor[3] ],
      'LeftPassandRollYourNeighbor' : [ PassAndRollYourNeighbor[4],PassAndRollYourNeighbor[5],PassAndRollYourNeighbor[6],PassAndRollYourNeighbor[7] ],
      'All8PassandRollYourNeighborandSpread' : [ PassAndRollYourNeighbor[8] ],
      'AsCouplesPassandRollYourNeighbor' : [ PassAndRollYourNeighbor[9] ],
      'PeelandTrail' : [ PeelAndTrail[0],PeelAndTrail[1],PeelAndTrail[2],PeelAndTrail[3],PeelAndTrail[4],PeelAndTrail[5],PeelAndTrail[6],PeelAndTrail[7],PeelAndTrail[8],PeelAndTrail[9],PeelAndTrail[10],PeelAndTrail[11],PeelAndTrail[12],PeelAndTrail[13],PeelAndTrail[14],PeelAndTrail[15],PeelAndTrail[16],PeelAndTrail[17],PeelAndTrail[18],PeelAndTrail[19],PeelAndTrail[20] ],
      'AsCouplesPeelandTrail' : [ PeelAndTrail[21],PeelAndTrail[22] ],
      'All8PeelandTrail' : [ PeelAndTrail[23] ],
      'Recycle' : [ Recycle[0],Recycle[1],Recycle[2] ],
      'ReverseRecycle' : [ Recycle[3],Recycle[4],Recycle[5] ],
      'AsCouplesReverseRecycle' : [ Recycle[7] ],
      'All8ReverseRecycle' : [ Recycle[9] ],
      'ScootandWeave' : [ ScootAndWeave[0],ScootAndWeave[1],ScootAndWeave[2],ScootAndWeave[3],ScootAndWeave[4],ScootAndWeave[5],ScootAndWeave[6],ScootAndWeave[7],ScootAndWeave[8],ScootAndWeave[9] ],
      'AsCouplesScootandWeave' : [ ScootAndWeave[10] ],
      'All8ScootandWeave' : [ ScootAndWeave[11] ],
      'ScootChainThru' : [ ScootChainThru[0],ScootChainThru[1],ScootChainThru[2],ScootChainThru[3] ],
      '12ScootChainThru' : [ ScootChainThru[4],ScootChainThru[5],ScootChainThru[6],ScootChainThru[7] ],
      'SingleWheel' : [ SingleWheel[0],SingleWheel[1],SingleWheel[2],SingleWheel[3],SingleWheel[4],SingleWheel[5],SingleWheel[6],SingleWheel[7],SingleWheel[8],SingleWheel[9],SingleWheel[10],SingleWheel[11],SingleWheel[12],SingleWheel[13],SingleWheel[14],SingleWheel[15],SingleWheel[16] ],
      'SingleWheel3Times' : [ SingleWheel[17] ],
      'Slip' : [ Slip[0],Slip[1],Slip[2],Slip[3],Slip[4],Slip[5],Slip[0],Slip[1],Slip[2],Slip[3],Slip[4],Slip[5],Slip[0],Slip[1],Slip[2],Slip[3],Slip[4],Slip[5],Slip[0],Slip[1],Slip[2],Slip[3],Slip[4],Slip[5] ],
      'AsCouplesSlip' : [ Slip[6],Slip[6],Slip[6],Slip[6] ],
      'All8Slip' : [ Slip[7],Slip[7],Slip[7],Slip[7] ],
      'Slide' : [ Slip[8],Slip[9],Slip[10],Slip[11],Slip[12],Slip[8],Slip[9],Slip[10],Slip[11],Slip[12],Slip[8],Slip[9],Slip[10],Slip[11],Slip[12],Slip[8],Slip[9],Slip[10],Slip[11],Slip[12] ],
      'AsCouplesSlide' : [ Slip[13],Slip[13],Slip[13],Slip[13] ],
      'All8Slide' : [ Slip[14],Slip[14],Slip[14],Slip[14] ],
      'Swing' : [ Slip[15],Slip[16],Slip[17],Slip[18],Slip[19],Slip[15],Slip[16],Slip[17],Slip[18],Slip[19],Slip[15],Slip[16],Slip[17],Slip[18],Slip[19],Slip[15],Slip[16],Slip[17],Slip[18],Slip[19] ],
      'AsCouplesSwing' : [ Slip[20],Slip[20],Slip[20],Slip[20] ],
      'All8Swing' : [ Slip[21],Slip[21],Slip[21],Slip[21] ],
      'Slither' : [ Slip[22],Slip[23],Slip[24],Slip[25],Slip[26],Slip[27],Slip[22],Slip[23],Slip[24],Slip[25],Slip[26],Slip[27],Slip[22],Slip[23],Slip[24],Slip[25],Slip[26],Slip[27],Slip[22],Slip[23],Slip[24],Slip[25],Slip[26],Slip[27] ],
      'AsCouplesSlither' : [ Slip[28],Slip[28],Slip[28],Slip[28] ],
      'All8Slither' : [ Slip[29],Slip[29],Slip[29],Slip[29] ],
      'SpintheWindmillRight' : [ SpinTheWindmill[0],SpinTheWindmill[1],SpinTheWindmill[2],SpinTheWindmill[3],SpinTheWindmill[4] ],
      'SpintheWindmillLeft' : [ SpinTheWindmill[5],SpinTheWindmill[6],SpinTheWindmill[7],SpinTheWindmill[8],SpinTheWindmill[9] ],
      'LeftSpintheWindmillRight' : [ SpinTheWindmill[10],SpinTheWindmill[11] ],
      'LeftSpintheWindmillLeft' : [ SpinTheWindmill[12],SpinTheWindmill[13] ],
      'SpintheWindmillForward' : [ SpinTheWindmill[14],SpinTheWindmill[19] ],
      'SpintheWindmillIn' : [ SpinTheWindmill[15],SpinTheWindmill[16] ],
      'SpintheWindmillOut' : [ SpinTheWindmill[17],SpinTheWindmill[18] ],
      'SwingandMix' : [ SwingAndMix[0],SwingAndMix[1],SwingAndMix[2],SwingAndMix[3],SwingAndMix[4],SwingAndMix[5],SwingAndMix[6],SwingAndMix[7],SwingAndMix[8],SwingAndMix[9],SwingAndMix[10],SwingAndMix[11],SwingAndMix[12] ],
      'LeftSwingandMix' : [ SwingAndMix[13],SwingAndMix[14],SwingAndMix[15] ],
      'All8SwingandMix' : [ SwingAndMix[16],SwingAndMix[17] ],
      'AsCouplesSwingandMix' : [ SwingAndMix[18] ],
      'SwitchtheWave' : [ SwitchTheWave[0],SwitchTheWave[1],SwitchTheWave[2],SwitchTheWave[3],SwitchTheWave[4],SwitchTheWave[5],SwitchTheWave[6],SwitchTheWave[7] ],
      'AsCouplesSwitchtheWave' : [ SwitchTheWave[8] ],
      'All8SwitchtheWave' : [ SwitchTheWave[9] ],
      'SwitchtoaDiamond' : [ SwitchToADiamond[0],SwitchToADiamond[1],SwitchToADiamond[2],SwitchToADiamond[3],SwitchToADiamond[4],SwitchToADiamond[5],SwitchToADiamond[0],SwitchToADiamond[1],SwitchToADiamond[2],SwitchToADiamond[3],SwitchToADiamond[4],SwitchToADiamond[5] ],
      'SwitchtoanHourglass' : [ SwitchToADiamond[6],SwitchToADiamond[7],SwitchToADiamond[6],SwitchToADiamond[7] ],
      'TradeCirculate' : [ TradeCirculate[0],TradeCirculate[1],TradeCirculate[2],TradeCirculate[3] ],
      'TrailOff' : [ TrailOff[0],TrailOff[1],TrailOff[2],TrailOff[3],TrailOff[4],TrailOff[5],TrailOff[6],TrailOff[7],TrailOff[8],TrailOff[9],TrailOff[10],TrailOff[11],TrailOff[12],TrailOff[13],TrailOff[14],TrailOff[15],TrailOff[16],TrailOff[17],TrailOff[18],TrailOff[19],TrailOff[20] ],
      'AsCouplesTrailOff' : [ TrailOff[21] ],
      'All8TrailOff' : [ TrailOff[22] ],
      'Transferand' : [ TransferAndAnything[0],TransferAndAnything[1],TransferAndAnything[2],TransferAndAnything[3],TransferAndAnything[4],TransferAndAnything[5] ],
      'TransferandBoxCirculateTwice' : [ TransferAndAnything[6] ],
      'TransferandBoxCounterRotate' : [ TransferAndAnything[7] ],
      'TransferandBoxTransfer' : [ TransferAndAnything[8] ],
      'TransferandCrossfire' : [ TransferAndAnything[9] ],
      'TransferandCuttheDiamond' : [ TransferAndAnything[10] ],
      'TransferandFollowYourNeighbor' : [ TransferAndAnything[11] ],
      'TransferandPeelandTrail' : [ TransferAndAnything[12] ],
      'TransferandPeeltheTop' : [ TransferAndAnything[13] ],
      'Transferand14Thru' : [ TransferAndAnything[14] ],
      'TransferandRemake' : [ TransferAndAnything[15] ],
      'TransferandSingleWheel' : [ TransferAndAnything[16] ],
      'TransferandTurnandDeal' : [ TransferAndAnything[17] ],
      'ZigZag' : [ ZigAndZag[0],ZigAndZag[1],ZigAndZag[2],ZigAndZag[3],ZigAndZag[4],ZigAndZag[5],ZigAndZag[6] ],
      'Zig' : [ ZigAndZag[7] ],
      'AsCouplesZigZag' : [ ZigAndZag[8] ],
      'AsCouplesZagZig' : [ ZigAndZag[9] ],
  };
}
