import '../../animated_call.dart';
import 'recycle.dart';
import 'ah_so.dart';
import 'alter_the_wave.dart';
import 'anything_and_spread.dart';
import 'anything_chain_thru.dart';
import 'anything_the_windmill.dart';
import 'anything_to_a_wave.dart';
import 'block_formation.dart';
import 'replace.dart';
import 'butterfly_formation.dart';
import 'cast_a_shadow.dart';
import 'cast_back.dart';
import 'chain_reaction.dart';
import 'chase_your_neighbor.dart';
import 'checkover.dart';
import 'circle_by.dart';
import 'circulate.dart';
import 'concentric_concept.dart';
import 'counter_rotate.dart';
import 'cross_and_turn.dart';
import 'cross_by.dart';
import 'cross_chain_thru.dart';
import 'cross_extend.dart';
import 'cross_over_circulate.dart';
import 'cross_roll.dart';
import 'cross_your_neighbor.dart';
import 'galaxy_formation.dart';
import 'interlocked_diamond_circulate.dart';
import 'dixie_diamond.dart';
import 'dixie_sashay.dart';
import 'finish.dart';
import 'tagging_calls_back_to_a_wave.dart';
import 'flip_the_line.dart';
import 'follow_thru.dart';
import 'ignore.dart';
import 'interrupt.dart';
import 'jaywalk.dart';
import 'linear_action.dart';
import 'scoot_and_little.dart';
import 'magic_column_formation.dart';
import 'make_magic.dart';
import 'o_formation.dart';
import 'pass_the_axle.dart';
import 'percolate.dart';
import 'phantom_formation.dart';
import 'scoot_and_plenty.dart';
import 'prefer.dart';
import 'press.dart';
import 'scoot_and_ramble.dart';
import 'regroup.dart';
import 'relay_the_shadow.dart';
import 'relay_the_top.dart';
import 'reverse_explode.dart';
import 'rotate.dart';
import 'wheel_and_anything.dart';
import 'rotary_spin.dart';
import 'scatter_scoot.dart';
import 'shakedown.dart';
import 'siamese_concept.dart';
import 'split_counter_rotate.dart';
import 'split_square_thru_variations.dart';
import 'square_chain_the_top.dart';
import 'square_the_bases.dart';
import 'squeeze.dart';
import 'start.dart';
import 'step_and_flip.dart';
import 'step_and_fold.dart';
import 'stretch_concept.dart';
import 'substitute.dart';
import 'swing_and_circle.dart';
import 'swing_the_fractions.dart';
import 'switch_the_line.dart';
import 'switch_to_a_diamond.dart';
import 'switch_to_an_hourglass.dart';
import 'switch_to_an_interlocked_diamond.dart';
import 't_bone_formation.dart';
import 'tally_ho.dart';
import 'tandem_concept.dart';
import 'three_by_two_acey_deucey.dart';
import 'track_n.dart';
import 'triangle_formation.dart';
import 'triple_box_concept.dart';
import 'twist_the_line.dart';
import 'vertical_tag.dart';
import 'anything_and_weave.dart';
import 'wheel_fan_thru.dart';
import 'with_the_flow.dart';
import 'zing.dart';
class CallsIndex {
  static Map<String,List<AnimatedCall>> index = {
      'RecycleIn3Parts' : [ Recycle[0],Recycle[1],Recycle[0],Recycle[1],Recycle[0],Recycle[1],Recycle[0],Recycle[1],Recycle[0],Recycle[1],Recycle[0],Recycle[1] ],
      'All8Recycle' : [ Recycle[2],Recycle[3],Recycle[4],Recycle[5],Recycle[6],Recycle[7],Recycle[8],Recycle[9],Recycle[2],Recycle[3],Recycle[4],Recycle[5],Recycle[6],Recycle[7],Recycle[8],Recycle[9],Recycle[2],Recycle[3],Recycle[4],Recycle[5],Recycle[6],Recycle[7],Recycle[8],Recycle[9],Recycle[2],Recycle[3],Recycle[4],Recycle[5],Recycle[6],Recycle[7],Recycle[8],Recycle[9],Recycle[2],Recycle[3],Recycle[4],Recycle[5],Recycle[6],Recycle[7],Recycle[8],Recycle[9],Recycle[2],Recycle[3],Recycle[4],Recycle[5],Recycle[6],Recycle[7],Recycle[8],Recycle[9] ],
      'All8CycleandWheel' : [ Recycle[10],Recycle[11],Recycle[12],Recycle[13],Recycle[14],Recycle[15],Recycle[16],Recycle[17],Recycle[10],Recycle[11],Recycle[12],Recycle[13],Recycle[14],Recycle[15],Recycle[16],Recycle[17],Recycle[10],Recycle[11],Recycle[12],Recycle[13],Recycle[14],Recycle[15],Recycle[16],Recycle[17],Recycle[10],Recycle[11],Recycle[12],Recycle[13],Recycle[14],Recycle[15],Recycle[16],Recycle[17],Recycle[10],Recycle[11],Recycle[12],Recycle[13],Recycle[14],Recycle[15],Recycle[16],Recycle[17],Recycle[10],Recycle[11],Recycle[12],Recycle[13],Recycle[14],Recycle[15],Recycle[16],Recycle[17] ],
      '23RecycleByDefinition' : [ Recycle[18],Recycle[19],Recycle[20],Recycle[21],Recycle[22],Recycle[23],Recycle[18],Recycle[19],Recycle[20],Recycle[21],Recycle[22],Recycle[23],Recycle[18],Recycle[19],Recycle[20],Recycle[21],Recycle[22],Recycle[23],Recycle[18],Recycle[19],Recycle[20],Recycle[21],Recycle[22],Recycle[23],Recycle[18],Recycle[19],Recycle[20],Recycle[21],Recycle[22],Recycle[23],Recycle[18],Recycle[19],Recycle[20],Recycle[21],Recycle[22],Recycle[23] ],
      '23Recycle' : [ Recycle[24],Recycle[25],Recycle[26],Recycle[27],Recycle[28],Recycle[29],Recycle[24],Recycle[25],Recycle[26],Recycle[27],Recycle[28],Recycle[29],Recycle[24],Recycle[25],Recycle[26],Recycle[27],Recycle[28],Recycle[29],Recycle[24],Recycle[25],Recycle[26],Recycle[27],Recycle[28],Recycle[29],Recycle[24],Recycle[25],Recycle[26],Recycle[27],Recycle[28],Recycle[29],Recycle[24],Recycle[25],Recycle[26],Recycle[27],Recycle[28],Recycle[29] ],
      'AsCouples23Recycle' : [ Recycle[30],Recycle[30],Recycle[30],Recycle[30],Recycle[30],Recycle[30] ],
      'Concentric23Recycle' : [ Recycle[31],Recycle[31],Recycle[31],Recycle[31],Recycle[31],Recycle[31] ],
      'Stretch23Recycle' : [ Recycle[32],Recycle[32],Recycle[32],Recycle[32],Recycle[32],Recycle[32] ],
      'Tandem23Recycle' : [ Recycle[33],Recycle[33],Recycle[33],Recycle[33],Recycle[33],Recycle[33] ],
      'BoxRecycle' : [ Recycle[34],Recycle[35],Recycle[34],Recycle[35],Recycle[34],Recycle[35],Recycle[34],Recycle[35],Recycle[34],Recycle[35],Recycle[34],Recycle[35] ],
      'SplitRecycle' : [ Recycle[36],Recycle[37],Recycle[38],Recycle[39],Recycle[40],Recycle[36],Recycle[37],Recycle[38],Recycle[39],Recycle[40],Recycle[36],Recycle[37],Recycle[38],Recycle[39],Recycle[40],Recycle[36],Recycle[37],Recycle[38],Recycle[39],Recycle[40],Recycle[36],Recycle[37],Recycle[38],Recycle[39],Recycle[40],Recycle[36],Recycle[37],Recycle[38],Recycle[39],Recycle[40] ],
      'AsCouplesBoxRecycle' : [ Recycle[41],Recycle[41],Recycle[41],Recycle[41],Recycle[41],Recycle[41] ],
      'All8BoxRecycle' : [ Recycle[42],Recycle[43],Recycle[42],Recycle[43],Recycle[42],Recycle[43],Recycle[42],Recycle[43],Recycle[42],Recycle[43],Recycle[42],Recycle[43] ],
      'ConcentricBoxRecycle' : [ Recycle[44],Recycle[44],Recycle[44],Recycle[44],Recycle[44],Recycle[44] ],
      'TandemBoxRecycle' : [ Recycle[45],Recycle[45],Recycle[45],Recycle[45],Recycle[45],Recycle[45] ],
      'TripleBoxRecycle' : [ Recycle[46],Recycle[46],Recycle[46],Recycle[46],Recycle[46],Recycle[46] ],
      'AhSo' : [ AhSo[0],AhSo[1],AhSo[2],AhSo[3],AhSo[4],AhSo[5],AhSo[6],AhSo[7],AhSo[8],AhSo[9],AhSo[10],AhSo[11],AhSo[12],AhSo[13],AhSo[14],AhSo[15],AhSo[16],AhSo[17],AhSo[18],AhSo[19],AhSo[20],AhSo[21],AhSo[22],AhSo[23],AhSo[24] ],
      'AsCouplesAhSo' : [ AhSo[25] ],
      'ConcentricAhSo' : [ AhSo[26] ],
      'StretchAhSo' : [ AhSo[27] ],
      'TandemAhSo' : [ AhSo[28] ],
      'AltertheWave' : [ AlterTheWave[0],AlterTheWave[1],AlterTheWave[2],AlterTheWave[3],AlterTheWave[4],AlterTheWave[5],AlterTheWave[6],AlterTheWave[7],AlterTheWave[8] ],
      'LeftAltertheWave' : [ AlterTheWave[9] ],
      'AltertheWaveButCounterRotatetheDiamond34' : [ AlterTheWave[10] ],
      'AsCouplesAltertheWave' : [ AlterTheWave[11] ],
      'All8AltertheWave' : [ AlterTheWave[12] ],
      'ConcentricAltertheWave' : [ AlterTheWave[13] ],
      'PhantomAltertheWave' : [ AlterTheWave[14] ],
      'TandemAltertheWave' : [ AlterTheWave[15] ],
      'Touch14BoySpread' : [ AnythingAndSpread[0] ],
      'All8RecycleChainThru' : [ AnythingChainThru[0] ],
      'CrossExtendChainThru' : [ AnythingChainThru[1] ],
      'InsideTriangleChainThru' : [ AnythingChainThru[3] ],
      'FollowThruChainThru' : [ AnythingChainThru[4] ],
      'FollowYourNeighborChainThru' : [ AnythingChainThru[5] ],
      'InterlockedDiamondChainThru' : [ AnythingChainThru[6] ],
      'PingPongChainThru' : [ AnythingChainThru[7] ],
      'SingleCircletoaWaveChainThru' : [ AnythingChainThru[8] ],
      'SplitRecycleChainThru' : [ AnythingChainThru[9] ],
      'MixtheWindmillRight' : [ AnythingTheWindmill[0] ],
      '12TagtheWindmillRight' : [ AnythingTheWindmill[1] ],
      'FollowYourNeighbortheWindmillForward' : [ AnythingTheWindmill[2] ],
      'SwitchtheWindmillRight' : [ AnythingTheWindmill[3] ],
      'FlipBacktoaWave' : [ AnythingToAWave[0],AnythingToAWave[1],AnythingToAWave[2],AnythingToAWave[3],AnythingToAWave[4],AnythingToAWave[5] ],
      'SquareChainThrutoaWave' : [ AnythingToAWave[6],AnythingToAWave[7],AnythingToAWave[8] ],
      'ScootChainThrutoaWave' : [ AnythingToAWave[9],AnythingToAWave[10],AnythingToAWave[11],AnythingToAWave[12] ],
      'SquareThru3toaWave' : [ AnythingToAWave[13] ],
      'LoadtheBoattoaWave' : [ AnythingToAWave[14] ],
      'PercolateOutsidetoaWave' : [ AnythingToAWave[15] ],
      'TagBacktoaWavetoaWave' : [ AnythingToAWave[16] ],
      'TurnThrutoaWave' : [ AnythingToAWave[17] ],
      'InYourBlockBoxCirculate' : [ BlockFormation[0] ],
      'InYourBlockChaseRight' : [ BlockFormation[1] ],
      'InYourBlockPassThru' : [ BlockFormation[2] ],
      'InYourBlockPartnerTag' : [ BlockFormation[3] ],
      'InYourBlockPartnerTrade' : [ BlockFormation[4] ],
      'InYourBlockSlideThru' : [ BlockFormation[5] ],
      'InYourBlockSquareChaintheTop' : [ BlockFormation[6] ],
      'InYourBlockSquareChainThru' : [ BlockFormation[7] ],
      'InYourBlockSquareThru' : [ BlockFormation[8] ],
      'InYourBlockTouch14' : [ BlockFormation[9] ],
      'InYourBlockWalkandDodge' : [ BlockFormation[10] ],
      'InYourBlockWheelThru' : [ BlockFormation[11] ],
      'InYourBlockZing' : [ BlockFormation[12] ],
      'SplitCounterRotate' : [ SplitCounterRotate[0],SplitCounterRotate[1] ],
      'ChainReactionBut23Recycle' : [ Replace[0],Replace[0],Replace[0],Replace[0] ],
      'ChainReactionReplacetheFinalCastOff34WithaSingleWheel' : [ Replace[1],Replace[1],Replace[1],Replace[1] ],
      'CoordinateReplaceTradeWithaRemake' : [ Replace[2],Replace[2],Replace[2],Replace[2] ],
      'DeleteAllArmTurn12SSpinChaintheGears' : [ Replace[3],Replace[3],Replace[3],Replace[3] ],
      'MotivateReplaceTurningtheStarWithaUTurnBack' : [ Replace[4],Replace[4],Replace[4],Replace[4] ],
      'PasstheAxleSkiptheThirdPart' : [ Replace[5],Replace[5],Replace[5],Replace[5] ],
      'ScootandPlentyReplacetheBoxCirculatesWithaMotivate' : [ Replace[6],Replace[6],Replace[6],Replace[6] ],
      'SwingtheFractionsReplacetheSecondPartWithTradeCirculate' : [ Replace[7],Replace[7],Replace[7],Replace[7] ],
      'SwingtheFractionsReplacetheThirdPartWithaSplitCirculate' : [ Replace[8],Replace[8],Replace[8],Replace[8] ],
      'TallyHoButExplodetheWave' : [ Replace[9],Replace[9],Replace[9],Replace[9] ],
      'ButterflyChaseRight' : [ ButterflyFormation[0] ],
      'ButterflyCheckmate' : [ ButterflyFormation[1] ],
      'ButterflyCirculate' : [ ButterflyFormation[2] ],
      'ButterflyCloverleaf' : [ ButterflyFormation[3] ],
      'ButterflyCoordinate' : [ ButterflyFormation[4] ],
      'ButterflyDoublePassThru' : [ ButterflyFormation[5] ],
      'ButterflyGrandRemake' : [ ButterflyFormation[6] ],
      'ButterflyHorseshoeTurn' : [ ButterflyFormation[7] ],
      'ButterflyPassIn' : [ ButterflyFormation[8] ],
      'ButterflyPassThru' : [ ButterflyFormation[9] ],
      'ButterflyPeelOff' : [ ButterflyFormation[10] ],
      'ButterflyRemake' : [ ButterflyFormation[11] ],
      'ButterflyRightRolltoaWave' : [ ButterflyFormation[12] ],
      'ButterflyScootBack' : [ ButterflyFormation[13] ],
      'ButterflySlideThru' : [ ButterflyFormation[14] ],
      'ButterflySplitCirculate' : [ ButterflyFormation[15] ],
      'ButterflySquareThru' : [ ButterflyFormation[16] ],
      'ButterflySwap' : [ ButterflyFormation[17] ],
      'ButterflySwingThru' : [ ButterflyFormation[18] ],
      'ButterflyTouch14' : [ ButterflyFormation[19] ],
      'ButterflyTrack2' : [ ButterflyFormation[20] ],
      'ButterflyTradeBy' : [ ButterflyFormation[21] ],
      'ButterflyTransfertheColumn' : [ ButterflyFormation[22] ],
      'ButterflyVeerLeft' : [ ButterflyFormation[23] ],
      'ButterflyWalkandDodge' : [ ButterflyFormation[24] ],
      'ButterflyWheelThru' : [ ButterflyFormation[25] ],
      'CastaShadow' : [ CastAShadow[0],CastAShadow[1] ],
      'CastBack' : [ CastBack[0],CastBack[1],CastBack[2],CastBack[3],CastBack[0],CastBack[1],CastBack[2],CastBack[3] ],
      'CrossCastBack' : [ CastBack[4],CastBack[4] ],
      'ChainReaction' : [ ChainReaction[2],ChainReaction[3],ChainReaction[4],ChainReaction[5],ChainReaction[6],ChainReaction[7] ],
      'ChainReactionTurntheStar12' : [ ChainReaction[9],ChainReaction[10],ChainReaction[11],ChainReaction[12],ChainReaction[13],ChainReaction[14],ChainReaction[15] ],
      'ChaseYourNeighbor' : [ ChaseYourNeighbor[0],ChaseYourNeighbor[1],ChaseYourNeighbor[2] ],
      'LeftChaseYourNeighbor' : [ ChaseYourNeighbor[3],ChaseYourNeighbor[4],ChaseYourNeighbor[5] ],
      'All8ChaseYourNeighbor' : [ ChaseYourNeighbor[6] ],
      'AsCouplesChaseYourNeighbor' : [ ChaseYourNeighbor[7] ],
      'ConcentricChaseYourNeighbor' : [ ChaseYourNeighbor[8] ],
      'TandemChaseYourNeighbor' : [ ChaseYourNeighbor[9] ],
      'TripleBoxChaseYourNeighbor' : [ ChaseYourNeighbor[10] ],
      'Checkover' : [ Checkover[0],Checkover[1] ],
      'CircleByNothingandNothing' : [ CircleBy[0] ],
      'CircleByNothingand14' : [ CircleBy[1] ],
      'CircleByNothingand12' : [ CircleBy[2] ],
      'CircleByNothingand34' : [ CircleBy[3] ],
      'CircleBy14andNothing' : [ CircleBy[4] ],
      'CircleBy14and14' : [ CircleBy[5] ],
      'CircleBy14and12' : [ CircleBy[6] ],
      'CircleBy14and34' : [ CircleBy[7] ],
      'CircleBy12andNothing' : [ CircleBy[8] ],
      'CircleBy12and14' : [ CircleBy[9] ],
      'CircleBy12and12' : [ CircleBy[10] ],
      'CircleBy12and34' : [ CircleBy[11] ],
      'CircleBy34andNothing' : [ CircleBy[12] ],
      'CircleBy34and14' : [ CircleBy[13] ],
      'CircleBy34and12' : [ CircleBy[14] ],
      'CircleBy34and34' : [ CircleBy[15] ],
      'BoxCirculate' : [ SiameseConcept[4] ],
      'Circulate' : [ Circulate[0],Circulate[1],Circulate[2],Circulate[3],TBoneFormation[0] ],
      'SplitCirculate' : [ TBoneFormation[1] ],
      'ConcentricBoxCounterRotate' : [ ConcentricConcept[0] ],
      'ConcentricBoxTransfer' : [ ConcentricConcept[1] ],
      'ConcentricChaseRight' : [ ConcentricConcept[2],ConcentricConcept[31] ],
      'ConcentricDixieStyletoaWave' : [ ConcentricConcept[3] ],
      'ConcentricDoPaso' : [ ConcentricConcept[4] ],
      'ConcentricDoubleStarThru' : [ ConcentricConcept[5] ],
      'ConcentricExtend' : [ ConcentricConcept[6] ],
      'ConcentricFlutterwheel' : [ ConcentricConcept[7] ],
      'ConcentricFollowYourNeighbor' : [ ConcentricConcept[8] ],
      'ConcentricLeadRight' : [ ConcentricConcept[9] ],
      'ConcentricPairOff' : [ ConcentricConcept[10] ],
      'ConcentricPassIn' : [ ConcentricConcept[11],ConcentricConcept[32] ],
      'ConcentricPassThru' : [ ConcentricConcept[12] ],
      'ConcentricPeelandTrail' : [ ConcentricConcept[13] ],
      'ConcentricPeelOff' : [ ConcentricConcept[14] ],
      'ConcentricPeeltheTop' : [ ConcentricConcept[15] ],
      'ConcentricRecycle' : [ ConcentricConcept[16],ConcentricConcept[53] ],
      'ConcentricRightandLeftThru' : [ ConcentricConcept[17],ConcentricConcept[36] ],
      'ConcentricScootBack' : [ ConcentricConcept[18] ],
      'ConcentricSlideThru' : [ ConcentricConcept[19],ConcentricConcept[37] ],
      'ConcentricStarThru' : [ ConcentricConcept[20],ConcentricConcept[38],ConcentricConcept[42] ],
      'ConcentricSquareThru' : [ ConcentricConcept[21],ConcentricConcept[39] ],
      'ConcentricTouch14' : [ ConcentricConcept[22],ConcentricConcept[40] ],
      'ConcentricTurnThru' : [ ConcentricConcept[23] ],
      'ConcentricWalkandDodge' : [ ConcentricConcept[24] ],
      'ConcentricZigZag' : [ ConcentricConcept[25] ],
      'ConcentricZoom' : [ ConcentricConcept[26],ConcentricConcept[41] ],
      'ConcentricCuttheDiamond' : [ ConcentricConcept[27] ],
      'ConcentricDiamondCirculate' : [ ConcentricConcept[28] ],
      'ConcentricFliptheDiamond' : [ ConcentricConcept[29] ],
      'ConcentricDiamondStepandFold' : [ ConcentricConcept[30],StepAndFold[20] ],
      'ConcentricPassOut' : [ ConcentricConcept[33] ],
      'ConcentricPasstheOcean' : [ ConcentricConcept[34] ],
      'ConcentricPasstheSea' : [ ConcentricConcept[35] ],
      'ConcentricCastOff34' : [ ConcentricConcept[43] ],
      'ConcentricBendtheLine' : [ ConcentricConcept[44] ],
      'ConcentricCrossfire' : [ ConcentricConcept[45] ],
      'ConcentricExplodetheWave' : [ ConcentricConcept[46] ],
      'ConcentricFantheTop' : [ ConcentricConcept[47] ],
      'Concentric12TagtheLine' : [ ConcentricConcept[48] ],
      'ConcentricHinge' : [ ConcentricConcept[49] ],
      'ConcentricLinearCycle' : [ ConcentricConcept[50] ],
      'ConcentricLockit' : [ ConcentricConcept[51] ],
      'ConcentricMix' : [ ConcentricConcept[52] ],
      'ConcentricSpintheTop' : [ ConcentricConcept[54] ],
      'ConcentricSwingThru' : [ ConcentricConcept[55] ],
      'ConcentricTradetheWave' : [ ConcentricConcept[56] ],
      'ConcentricTurnandDeal' : [ ConcentricConcept[57] ],
      'ConcentricVeerRight' : [ ConcentricConcept[58] ],
      'ConcentricWheelandDeal' : [ ConcentricConcept[59],ConcentricConcept[60],ConcentricConcept[61],ConcentricConcept[62] ],
      'CounterRotate' : [ CounterRotate[0],CounterRotate[1],CounterRotate[2],CounterRotate[3],CounterRotate[4],CounterRotate[5],CounterRotate[6],CounterRotate[7],CounterRotate[8],CounterRotate[9],CounterRotate[10],CounterRotate[11],CounterRotate[12],CounterRotate[13],CounterRotate[14],CounterRotate[15],CounterRotate[16] ],
      'PointCounterRotate' : [ CounterRotate[17] ],
      'CrossandTurn' : [ CrossAndTurn[0],CrossAndTurn[1],CrossAndTurn[2],CrossAndTurn[0],CrossAndTurn[1],CrossAndTurn[2] ],
      'AsCouplesCrossandTurn' : [ CrossAndTurn[3],CrossAndTurn[3] ],
      'All8CrossandTurn' : [ CrossAndTurn[4],CrossAndTurn[4] ],
      'ButterflyCrossandTurn' : [ CrossAndTurn[5],CrossAndTurn[5] ],
      'ConcentricCrossandTurn' : [ CrossAndTurn[6],CrossAndTurn[6] ],
      'OCrossandTurn' : [ CrossAndTurn[7],CrossAndTurn[7] ],
      'ReverseCrossandTurn' : [ CrossAndTurn[8],CrossAndTurn[9],CrossAndTurn[10],CrossAndTurn[8],CrossAndTurn[9],CrossAndTurn[10] ],
      'AsCouplesReverseCrossandTurn' : [ CrossAndTurn[11],CrossAndTurn[11] ],
      'All8ReverseCrossandTurn' : [ CrossAndTurn[12],CrossAndTurn[12] ],
      'ButterflyReverseCrossandTurn' : [ CrossAndTurn[13],CrossAndTurn[13] ],
      'ConcentricReverseCrossandTurn' : [ CrossAndTurn[14],CrossAndTurn[14] ],
      'OReverseCrossandTurn' : [ CrossAndTurn[15],CrossAndTurn[15] ],
      'CrossBy' : [ CrossBy[0],CrossBy[1],CrossBy[2] ],
      'CrossChainThru' : [ CrossChainThru[0],CrossChainThru[0] ],
      'CrossChainandRoll' : [ CrossChainThru[1],CrossChainThru[1] ],
      'CrossExtend' : [ CrossExtend[0],CrossExtend[1],CrossExtend[2],CrossExtend[3],CrossExtend[4],CrossExtend[5] ],
      'AsCouplesCrossExtend' : [ CrossExtend[6] ],
      'TandemCrossExtend' : [ CrossExtend[7] ],
      'CrossOverCirculate' : [ CrossOverCirculate[0],CrossOverCirculate[1],CrossOverCirculate[2],CrossOverCirculate[3] ],
      'CrossRoll' : [ CrossRoll[0],CrossRoll[1],CrossRoll[2],CrossRoll[3],CrossRoll[4],CrossRoll[5],CrossRoll[6],CrossRoll[7],CrossRoll[8],CrossRoll[9],CrossRoll[10],CrossRoll[11],CrossRoll[12],CrossRoll[13],CrossRoll[14],CrossRoll[15],CrossRoll[16],CrossRoll[17],CrossRoll[18],CrossRoll[19],CrossRoll[20],CrossRoll[21],CrossRoll[22],CrossRoll[23],CrossRoll[24],CrossRoll[25],CrossRoll[26],CrossRoll[27],CrossRoll[28],CrossRoll[29],CrossRoll[30],CrossRoll[31],CrossRoll[32],CrossRoll[33],CrossRoll[34],CrossRoll[35],CrossRoll[36],CrossRoll[37],CrossRoll[38],CrossRoll[39] ],
      'All8CrossRoll' : [ CrossRoll[40],CrossRoll[41] ],
      'AsCouplesCrossRoll' : [ CrossRoll[42] ],
      'ConcentricCrossRoll' : [ CrossRoll[43] ],
      'TandemCrossRoll' : [ CrossRoll[44] ],
      'CrossYourNeighbor' : [ CrossYourNeighbor[0],CrossYourNeighbor[1],CrossYourNeighbor[2],CrossYourNeighbor[3],CrossYourNeighbor[4],CrossYourNeighbor[5],CrossYourNeighbor[6],CrossYourNeighbor[7],CrossYourNeighbor[0],CrossYourNeighbor[1],CrossYourNeighbor[2],CrossYourNeighbor[3],CrossYourNeighbor[4],CrossYourNeighbor[5],CrossYourNeighbor[6],CrossYourNeighbor[7] ],
      'GrandCrossYourNeighbor' : [ CrossYourNeighbor[8],CrossYourNeighbor[9],CrossYourNeighbor[8],CrossYourNeighbor[9] ],
      'All8CrossYourNeighbor' : [ CrossYourNeighbor[10],CrossYourNeighbor[10] ],
      'AsCouplesCrossYourNeighbor' : [ CrossYourNeighbor[11],CrossYourNeighbor[11] ],
      'TandemCrossYourNeighbor' : [ CrossYourNeighbor[12],CrossYourNeighbor[12] ],
      'PassandRollYourCrossNeighbor' : [ CrossYourNeighbor[13],CrossYourNeighbor[13] ],
      'LeftPassandRollYourCrossNeighbor' : [ CrossYourNeighbor[14],CrossYourNeighbor[14] ],
      'GalaxyCirculate' : [ GalaxyFormation[0],GalaxyFormation[1],GalaxyFormation[2],GalaxyFormation[3],GalaxyFormation[0],GalaxyFormation[1],GalaxyFormation[2],GalaxyFormation[3],GalaxyFormation[0],GalaxyFormation[1],GalaxyFormation[2],GalaxyFormation[3],GalaxyFormation[0],GalaxyFormation[1],GalaxyFormation[2],GalaxyFormation[3] ],
      'CuttheGalaxy' : [ GalaxyFormation[4],GalaxyFormation[5],GalaxyFormation[6],GalaxyFormation[7],GalaxyFormation[4],GalaxyFormation[5],GalaxyFormation[6],GalaxyFormation[7],GalaxyFormation[4],GalaxyFormation[5],GalaxyFormation[6],GalaxyFormation[7],GalaxyFormation[4],GalaxyFormation[5],GalaxyFormation[6],GalaxyFormation[7] ],
      'FliptheGalaxy' : [ GalaxyFormation[8],GalaxyFormation[9],GalaxyFormation[10],GalaxyFormation[11],GalaxyFormation[8],GalaxyFormation[9],GalaxyFormation[10],GalaxyFormation[11],GalaxyFormation[8],GalaxyFormation[9],GalaxyFormation[10],GalaxyFormation[11],GalaxyFormation[8],GalaxyFormation[9],GalaxyFormation[10],GalaxyFormation[11] ],
      'InterlockedDiamondCirculate' : [ InterlockedDiamondCirculate[0],InterlockedDiamondCirculate[1],InterlockedDiamondCirculate[2],InterlockedDiamondCirculate[3],InterlockedDiamondCirculate[4],InterlockedDiamondCirculate[5],InterlockedDiamondCirculate[6],InterlockedDiamondCirculate[7],InterlockedDiamondCirculate[0],InterlockedDiamondCirculate[1],InterlockedDiamondCirculate[2],InterlockedDiamondCirculate[3],InterlockedDiamondCirculate[4],InterlockedDiamondCirculate[5],InterlockedDiamondCirculate[6],InterlockedDiamondCirculate[7],InterlockedDiamondCirculate[0],InterlockedDiamondCirculate[1],InterlockedDiamondCirculate[2],InterlockedDiamondCirculate[3],InterlockedDiamondCirculate[4],InterlockedDiamondCirculate[5],InterlockedDiamondCirculate[6],InterlockedDiamondCirculate[7] ],
      'CuttheInterlockedDiamond' : [ InterlockedDiamondCirculate[8],InterlockedDiamondCirculate[9],InterlockedDiamondCirculate[10],InterlockedDiamondCirculate[11],InterlockedDiamondCirculate[12],InterlockedDiamondCirculate[13],InterlockedDiamondCirculate[14],InterlockedDiamondCirculate[15],InterlockedDiamondCirculate[8],InterlockedDiamondCirculate[9],InterlockedDiamondCirculate[10],InterlockedDiamondCirculate[11],InterlockedDiamondCirculate[12],InterlockedDiamondCirculate[13],InterlockedDiamondCirculate[14],InterlockedDiamondCirculate[15],InterlockedDiamondCirculate[8],InterlockedDiamondCirculate[9],InterlockedDiamondCirculate[10],InterlockedDiamondCirculate[11],InterlockedDiamondCirculate[12],InterlockedDiamondCirculate[13],InterlockedDiamondCirculate[14],InterlockedDiamondCirculate[15] ],
      'FliptheInterlockedDiamond' : [ InterlockedDiamondCirculate[16],InterlockedDiamondCirculate[17],InterlockedDiamondCirculate[18],InterlockedDiamondCirculate[19],InterlockedDiamondCirculate[20],InterlockedDiamondCirculate[21],InterlockedDiamondCirculate[22],InterlockedDiamondCirculate[23],InterlockedDiamondCirculate[16],InterlockedDiamondCirculate[17],InterlockedDiamondCirculate[18],InterlockedDiamondCirculate[19],InterlockedDiamondCirculate[20],InterlockedDiamondCirculate[21],InterlockedDiamondCirculate[22],InterlockedDiamondCirculate[23],InterlockedDiamondCirculate[16],InterlockedDiamondCirculate[17],InterlockedDiamondCirculate[18],InterlockedDiamondCirculate[19],InterlockedDiamondCirculate[20],InterlockedDiamondCirculate[21],InterlockedDiamondCirculate[22],InterlockedDiamondCirculate[23] ],
      'DixieDiamond' : [ DixieDiamond[0],DixieDiamond[1],DixieDiamond[2],DixieDiamond[3],DixieDiamond[4] ],
      'All8DixieDiamond' : [ DixieDiamond[5] ],
      'AsCouplesDixieDiamond' : [ DixieDiamond[6] ],
      'DixieDiamondInterruptWithFlipBack' : [ DixieDiamond[7] ],
      'ReverseDixieDiamond' : [ DixieDiamond[8] ],
      'DixieSashay' : [ DixieSashay[0],DixieSashay[1],DixieSashay[2],DixieSashay[3],DixieSashay[4],DixieSashay[5] ],
      'All8DixieSashay' : [ DixieSashay[6] ],
      'FinishAltertheWave' : [ Finish[0] ],
      'FinishBraceThru' : [ Finish[1] ],
      'FinishCoordinate' : [ Finish[2] ],
      'FinishCrossChainandRoll' : [ Finish[3] ],
      'FinishDiamondChainThru' : [ Finish[4] ],
      'FinishDixieDiamond' : [ Finish[5] ],
      'FinishLinearCycle' : [ Finish[6] ],
      'FinishLoadtheBoat' : [ Finish[7] ],
      'FinishMotivate' : [ Finish[8] ],
      'FinishPassandRoll' : [ Finish[9] ],
      'FinishPasstheOcean' : [ Finish[10] ],
      'FinishPasstheSea' : [ Finish[11] ],
      'FinishPercolate' : [ Finish[12] ],
      'FinishRecycle' : [ Finish[13] ],
      'FinishRelaytheDeucey' : [ Finish[14] ],
      'FinishRelaytheShadow' : [ Finish[15] ],
      'FinishRelaytheTop' : [ Finish[16] ],
      'FinishRemake' : [ Finish[17] ],
      'FinishRotarySpin' : [ Finish[18] ],
      'FinishSpinChainandExchangetheGears' : [ Finish[19] ],
      'FinishSpinChaintheGears' : [ Finish[20] ],
      'FinishSpinChainThru' : [ Finish[21] ],
      'FinishSwingtheFractions' : [ Finish[22] ],
      'FinishTallyHo' : [ Finish[23] ],
      'FinishTripleStarThru' : [ Finish[24] ],
      'FlipBack' : [ TaggingCallsBackToAWave[0],TaggingCallsBackToAWave[1],TaggingCallsBackToAWave[2],TaggingCallsBackToAWave[3],TaggingCallsBackToAWave[4],TaggingCallsBackToAWave[5],TaggingCallsBackToAWave[0],TaggingCallsBackToAWave[1],TaggingCallsBackToAWave[2],TaggingCallsBackToAWave[3],TaggingCallsBackToAWave[4],TaggingCallsBackToAWave[5],TaggingCallsBackToAWave[0],TaggingCallsBackToAWave[1],TaggingCallsBackToAWave[2],TaggingCallsBackToAWave[3],TaggingCallsBackToAWave[4],TaggingCallsBackToAWave[5] ],
      'TagBacktoaWave' : [ TaggingCallsBackToAWave[6],TaggingCallsBackToAWave[7],TaggingCallsBackToAWave[6],TaggingCallsBackToAWave[7],TaggingCallsBackToAWave[6],TaggingCallsBackToAWave[7] ],
      'VerticalTagBacktoaWave' : [ TaggingCallsBackToAWave[8],TaggingCallsBackToAWave[8],TaggingCallsBackToAWave[8] ],
      'All8VerticalTagBacktoaWave' : [ TaggingCallsBackToAWave[9],TaggingCallsBackToAWave[9],TaggingCallsBackToAWave[9] ],
      'FliptheLine14' : [ FlipTheLine[0],FlipTheLine[1],FlipTheLine[2],FlipTheLine[3],FlipTheLine[4],FlipTheLine[5] ],
      'FliptheLine12' : [ FlipTheLine[6],FlipTheLine[7],FlipTheLine[8],FlipTheLine[9],FlipTheLine[10],FlipTheLine[11] ],
      'FliptheLine34' : [ FlipTheLine[12],FlipTheLine[13],FlipTheLine[14],FlipTheLine[15],FlipTheLine[16],FlipTheLine[17] ],
      'FliptheLine' : [ FlipTheLine[18],FlipTheLine[19],FlipTheLine[20],FlipTheLine[21],FlipTheLine[22],FlipTheLine[23] ],
      'ConcentricFliptheLine14' : [ FlipTheLine[24] ],
      'ConcentricFliptheLine12' : [ FlipTheLine[25] ],
      'ConcentricFliptheLine34' : [ FlipTheLine[26] ],
      'ConcentricFliptheLine' : [ FlipTheLine[27] ],
      'TandemFliptheLine14' : [ FlipTheLine[28] ],
      'TandemFliptheLine12' : [ FlipTheLine[29] ],
      'FollowThru' : [ FollowThru[0],FollowThru[1],FollowThru[2],FollowThru[3],FollowThru[4],FollowThru[5],FollowThru[6],FollowThru[7],FollowThru[8],FollowThru[9],FollowThru[10],FollowThru[11],FollowThru[12],FollowThru[13] ],
      'GrandFollowThru' : [ FollowThru[14],FollowThru[15] ],
      'All8FollowThru' : [ FollowThru[16] ],
      'AsCouplesFollowThru' : [ FollowThru[17],FollowThru[18] ],
      'ConcentricFollowThru' : [ FollowThru[19] ],
      'StretchFollowThru' : [ FollowThru[20] ],
      'TandemFollowThru' : [ FollowThru[21] ],
      'FollowYourNeighbor' : [ TBoneFormation[3] ],
      'IgnoretheVeryCenterFantheTop' : [ Ignore[0] ],
      'IgnoretheHeadBoyMotivate' : [ Ignore[1] ],
      'IgnoretheLeadEndLinesOf3OutRollCirculate' : [ Ignore[2] ],
      'IgnoretheHeadBoyWaveBasedTriangleCirculate' : [ Ignore[3] ],
      'ScootandPlentyInterruptBeforetheSplitCirculatesWithanAceyDeucey' : [ Interrupt[0] ],
      'SquareChainThruInterruptBeforetheLastPartWithSpintheTop' : [ Interrupt[1] ],
      'SquareThruInterrupton3WithaSwingThru' : [ Interrupt[2] ],
      'SwingtheFractionsInterruptAfter35WithTradeCirculate' : [ Interrupt[3] ],
      'BoyJaywalk' : [ Jaywalk[0] ],
      'Jaywalk' : [ Jaywalk[1],Jaywalk[2],Jaywalk[3],Jaywalk[4],Jaywalk[5] ],
      'LinearAction' : [ LinearAction[0],LinearAction[1],LinearAction[2],LinearAction[3],LinearAction[4],LinearAction[5],LinearAction[6],LinearAction[7],LinearAction[8],LinearAction[9],LinearAction[10],LinearAction[11],LinearAction[12],LinearAction[13],LinearAction[14],LinearAction[15] ],
      'Little' : [ ScootAndLittle[0],ScootAndLittle[1],ScootAndLittle[2],ScootAndLittle[3],ScootAndLittle[4],ScootAndLittle[5],ScootAndLittle[6],ScootAndLittle[7],ScootAndLittle[8],ScootAndLittle[0],ScootAndLittle[1],ScootAndLittle[2],ScootAndLittle[3],ScootAndLittle[4],ScootAndLittle[5],ScootAndLittle[6],ScootAndLittle[7],ScootAndLittle[8] ],
      'LittlePointGoAsYouAre' : [ ScootAndLittle[9],ScootAndLittle[9] ],
      'LittleOutsideOut' : [ ScootAndLittle[10],ScootAndLittle[10] ],
      'LeftLittle' : [ ScootAndLittle[11],ScootAndLittle[12],ScootAndLittle[13],ScootAndLittle[14],ScootAndLittle[15],ScootAndLittle[11],ScootAndLittle[12],ScootAndLittle[13],ScootAndLittle[14],ScootAndLittle[15] ],
      'ScootandLittle' : [ ScootAndLittle[16],ScootAndLittle[17],ScootAndLittle[16],ScootAndLittle[17] ],
      'MagicCirculate' : [ MagicColumnFormation[0],MagicColumnFormation[1],MagicColumnFormation[7],MagicColumnFormation[8],MagicColumnFormation[0],MagicColumnFormation[1],MagicColumnFormation[7],MagicColumnFormation[8] ],
      'MagicCoordinate' : [ MagicColumnFormation[2],MagicColumnFormation[9],MagicColumnFormation[2],MagicColumnFormation[9] ],
      'MagicSplitCirculate' : [ MagicColumnFormation[3],MagicColumnFormation[10],MagicColumnFormation[3],MagicColumnFormation[10] ],
      'MagicTransfertheColumn' : [ MagicColumnFormation[4],MagicColumnFormation[11],MagicColumnFormation[4],MagicColumnFormation[11] ],
      'MagicTransferand' : [ MagicColumnFormation[5],MagicColumnFormation[12],MagicColumnFormation[5],MagicColumnFormation[12] ],
      'MagicWalkandDodge' : [ MagicColumnFormation[6],MagicColumnFormation[13],MagicColumnFormation[6],MagicColumnFormation[13] ],
      'MakeMagic' : [ MakeMagic[0],MakeMagic[1] ],
      'OChaseRight' : [ OFormation[0] ],
      'OCirculate' : [ OFormation[1],OFormation[2],OFormation[3],OFormation[4] ],
      'OCloverleaf' : [ OFormation[5] ],
      'OCoordinate' : [ OFormation[6] ],
      'ODoublePassThru' : [ OFormation[7] ],
      'OPassIn' : [ OFormation[8] ],
      'OPassThru' : [ OFormation[9] ],
      'OPeelOff' : [ OFormation[10] ],
      'ORightRolltoaWave' : [ OFormation[11] ],
      'OScootBack' : [ OFormation[12] ],
      'OSlideThru' : [ OFormation[13] ],
      'OSquareThru' : [ OFormation[14] ],
      'OSplitCirculate' : [ OFormation[15] ],
      'OSplitCounterRotate' : [ OFormation[16] ],
      'OSwap' : [ OFormation[17] ],
      'OSwingThru' : [ OFormation[18] ],
      'OTouch14' : [ OFormation[19] ],
      'OTrack2' : [ OFormation[20] ],
      'OTradeBy' : [ OFormation[21] ],
      'OTransfertheColumn' : [ OFormation[22] ],
      'OVeerLeft' : [ OFormation[23] ],
      'OWalkandDodge' : [ OFormation[24] ],
      'OWheelThru' : [ OFormation[25] ],
      'OZoom' : [ OFormation[26] ],
      'MagicOCirculate' : [ OFormation[33],OFormation[34] ],
      'MagicOWalkandDodge' : [ OFormation[35] ],
      'PasstheAxle' : [ PassTheAxle[0],PassTheAxle[0] ],
      'theAxle' : [ PassTheAxle[1],PassTheAxle[2],PassTheAxle[1],PassTheAxle[2] ],
      'Percolate' : [ Percolate[0],Percolate[1],Percolate[2],Percolate[3],Percolate[4],Percolate[5] ],
      'PercolateButAhSo' : [ Percolate[6] ],
      'PercolateButSwingThru' : [ Percolate[7] ],
      'PercolateBut23Recycle' : [ Percolate[8] ],
      'PhantomAceyDeucey' : [ PhantomFormation[0] ],
      'PhantomCirculate' : [ PhantomFormation[1],PhantomFormation[3] ],
      'PhantomBendtheLines' : [ PhantomFormation[2] ],
      'PhantomFerrisWheel' : [ PhantomFormation[4] ],
      'PhantomLoadtheBoat' : [ PhantomFormation[5] ],
      'PhantomMotivate' : [ PhantomFormation[6] ],
      'PhantomPassThru' : [ PhantomFormation[7] ],
      'PhantomTallyHo' : [ PhantomFormation[8] ],
      'PhantomTradeCirculate' : [ PhantomFormation[9] ],
      'PhantomWheelandDeal' : [ PhantomFormation[10] ],
      'Plenty' : [ ScootAndPlenty[0],ScootAndPlenty[1],ScootAndPlenty[2],ScootAndPlenty[3],ScootAndPlenty[4],ScootAndPlenty[5],ScootAndPlenty[0],ScootAndPlenty[1],ScootAndPlenty[2],ScootAndPlenty[3],ScootAndPlenty[4],ScootAndPlenty[5] ],
      'PlentyPointGoAsYouAre' : [ ScootAndPlenty[6],ScootAndPlenty[6] ],
      'LeftPlenty' : [ ScootAndPlenty[7],ScootAndPlenty[8],ScootAndPlenty[9],ScootAndPlenty[10],ScootAndPlenty[7],ScootAndPlenty[8],ScootAndPlenty[9],ScootAndPlenty[10] ],
      'ScootandPlenty' : [ ScootAndPlenty[11],ScootAndPlenty[12],ScootAndPlenty[11],ScootAndPlenty[12] ],
      'PrefertheBoyExplodetheLine' : [ Prefer[0] ],
      'PrefertheHeadBoyInRollCirculate' : [ Prefer[1] ],
      'PrefertheGirlScootandDodge' : [ Prefer[2] ],
      'PressAhead' : [ Press[0],Press[1],Press[2],Press[3],Press[4],Press[5] ],
      'EndPressAhead' : [ Press[6] ],
      'GirlPressAhead' : [ Press[7] ],
      '12PressAhead' : [ Press[8],Press[9],Press[10],Press[11] ],
      'Ramble' : [ ScootAndRamble[0],ScootAndRamble[1],ScootAndRamble[2],ScootAndRamble[3],ScootAndRamble[4],ScootAndRamble[5],ScootAndRamble[6],ScootAndRamble[0],ScootAndRamble[1],ScootAndRamble[2],ScootAndRamble[3],ScootAndRamble[4],ScootAndRamble[5],ScootAndRamble[6] ],
      'ScootandRamble' : [ ScootAndRamble[7],ScootAndRamble[8],ScootAndRamble[9],ScootAndRamble[7],ScootAndRamble[8],ScootAndRamble[9] ],
      'Regroup' : [ Regroup[0],Regroup[1] ],
      'RelaytheShadow' : [ RelayTheShadow[0],RelayTheShadow[1],RelayTheShadow[2] ],
      'RelaytheTop' : [ RelayTheTop[0],RelayTheTop[1],RelayTheTop[2] ],
      'LeftRelaytheTop' : [ RelayTheTop[3] ],
      'RelaytheTopTurntheStar12' : [ RelayTheTop[4],RelayTheTop[7] ],
      'RelaytheTopTurntheStar34' : [ RelayTheTop[5],RelayTheTop[8] ],
      'RelaytheTopDoNotTurntheStar' : [ RelayTheTop[6],RelayTheTop[9] ],
      'ReverseExplode' : [ ReverseExplode[0],ReverseExplode[1],ReverseExplode[2],ReverseExplode[3],ReverseExplode[4],ReverseExplode[5] ],
      'All8ReverseExplode' : [ ReverseExplode[6] ],
      'AsCouplesReverseExplode' : [ ReverseExplode[7] ],
      'ConcentricReverseExplode' : [ ReverseExplode[8] ],
      'StretchReverseExplode' : [ ReverseExplode[9] ],
      'TandemReverseExplode' : [ ReverseExplode[10] ],
      'HeadRotate' : [ Rotate[0],Rotate[0],Rotate[0],Rotate[0] ],
      'SideRotate' : [ Rotate[1],Rotate[1],Rotate[1],Rotate[1] ],
      'HeadRotate12' : [ Rotate[2],Rotate[2],Rotate[2],Rotate[2] ],
      'SideRotate12' : [ Rotate[3],Rotate[3],Rotate[3],Rotate[3] ],
      'HeadReverseRotate' : [ Rotate[4],Rotate[4],Rotate[4],Rotate[4] ],
      'SideReverseRotate' : [ Rotate[5],Rotate[5],Rotate[5],Rotate[5] ],
      'HeadReverseRotate12' : [ Rotate[6],Rotate[6],Rotate[6],Rotate[6] ],
      'SideReverseRotate12' : [ Rotate[7],Rotate[7],Rotate[7],Rotate[7] ],
      'HeadSingleRotate' : [ Rotate[8],Rotate[8],Rotate[8],Rotate[8] ],
      'SideSingleRotate' : [ Rotate[9],Rotate[9],Rotate[9],Rotate[9] ],
      'HeadSingleRotate12' : [ Rotate[10],Rotate[10],Rotate[10],Rotate[10] ],
      'SideSingleRotate12' : [ Rotate[11],Rotate[11],Rotate[11],Rotate[11] ],
      'HeadReverseSingleRotate' : [ Rotate[12],Rotate[12],Rotate[12],Rotate[12] ],
      'SideReverseSingleRotate' : [ Rotate[13],Rotate[13],Rotate[13],Rotate[13] ],
      'HeadReverseSingleRotate12' : [ Rotate[14],Rotate[14],Rotate[14],Rotate[14] ],
      'SideReverseSingleRotate12' : [ Rotate[15],Rotate[15],Rotate[15],Rotate[15] ],
      'Wheel' : [ WheelAndAnything[0],WheelAndAnything[0] ],
      'ReverseWheel' : [ WheelAndAnything[1],WheelAndAnything[1] ],
      'WheelandSpintheTop' : [ WheelAndAnything[2],WheelAndAnything[2] ],
      'WheelandTouch14' : [ WheelAndAnything[3],WheelAndAnything[3] ],
      'ReverseWheelandTouch14' : [ WheelAndAnything[4],WheelAndAnything[4] ],
      'RotarySpin' : [ RotarySpin[0],RotarySpin[1] ],
      'ORotarySpin' : [ RotarySpin[2] ],
      'ScatterScoot' : [ ScatterScoot[0],ScatterScoot[1],ScatterScoot[2],ScatterScoot[3],ScatterScoot[0],ScatterScoot[1],ScatterScoot[2],ScatterScoot[3] ],
      'ScatterScootChainThru' : [ ScatterScoot[4],ScatterScoot[5],ScatterScoot[4],ScatterScoot[5] ],
      'ScootBack' : [ TBoneFormation[2] ],
      'Shakedown' : [ Shakedown[0],Shakedown[1],Shakedown[2] ],
      'LeftShakedown' : [ Shakedown[3],Shakedown[4],Shakedown[5] ],
      'All8Shakedown' : [ Shakedown[6] ],
      'AsCouplesShakedown' : [ Shakedown[7] ],
      'ButterflyShakedown' : [ Shakedown[8] ],
      'ConcentricShakedown' : [ Shakedown[9] ],
      'OShakedown' : [ Shakedown[10] ],
      'StretchShakedown' : [ Shakedown[11],Shakedown[12],StretchConcept[14] ],
      'AsCouplesLeftShakedown' : [ Shakedown[13] ],
      'ConcentricLeftShakedown' : [ Shakedown[14] ],
      'StretchLeftShakedown' : [ Shakedown[15],Shakedown[16] ],
      'Siamese23Recycle' : [ SiameseConcept[0] ],
      'SiameseAhSo' : [ SiameseConcept[1] ],
      'SiameseAltertheWave' : [ SiameseConcept[2] ],
      'SiameseBendtheLine' : [ SiameseConcept[3] ],
      'SiameseCrossYourNeighbor' : [ SiameseConcept[5] ],
      'SiameseDiamondCirculate' : [ SiameseConcept[6] ],
      'SiameseDixieStyletoaWave' : [ SiameseConcept[7] ],
      'SiameseFollowThru' : [ SiameseConcept[8] ],
      'SiameseMix' : [ SiameseConcept[9] ],
      'SiamesePasstheOcean' : [ SiameseConcept[10] ],
      'SiameseRecycle' : [ SiameseConcept[11] ],
      'SiameseSpintheTop' : [ SiameseConcept[12] ],
      'SiameseZing' : [ SiameseConcept[13] ],
      'SplitSquareChaintheTop' : [ SplitSquareThruVariations[0],SplitSquareThruVariations[1],SplitSquareThruVariations[2],SplitSquareThruVariations[3],SplitSquareThruVariations[4],SplitSquareThruVariations[0],SplitSquareThruVariations[1],SplitSquareThruVariations[2],SplitSquareThruVariations[3],SplitSquareThruVariations[4],SplitSquareThruVariations[0],SplitSquareThruVariations[1],SplitSquareThruVariations[2],SplitSquareThruVariations[3],SplitSquareThruVariations[4],SplitSquareThruVariations[0],SplitSquareThruVariations[1],SplitSquareThruVariations[2],SplitSquareThruVariations[3],SplitSquareThruVariations[4] ],
      'SplitDixieStyletoaWave' : [ SplitSquareThruVariations[5],SplitSquareThruVariations[6],SplitSquareThruVariations[7],SplitSquareThruVariations[8],SplitSquareThruVariations[5],SplitSquareThruVariations[6],SplitSquareThruVariations[7],SplitSquareThruVariations[8],SplitSquareThruVariations[5],SplitSquareThruVariations[6],SplitSquareThruVariations[7],SplitSquareThruVariations[8],SplitSquareThruVariations[5],SplitSquareThruVariations[6],SplitSquareThruVariations[7],SplitSquareThruVariations[8] ],
      'SplitDixieDiamond' : [ SplitSquareThruVariations[9],SplitSquareThruVariations[10],SplitSquareThruVariations[9],SplitSquareThruVariations[10],SplitSquareThruVariations[9],SplitSquareThruVariations[10],SplitSquareThruVariations[9],SplitSquareThruVariations[10] ],
      'SplitDixieSashay' : [ SplitSquareThruVariations[11],SplitSquareThruVariations[12],SplitSquareThruVariations[11],SplitSquareThruVariations[12],SplitSquareThruVariations[11],SplitSquareThruVariations[12],SplitSquareThruVariations[11],SplitSquareThruVariations[12] ],
      'LeftSplitSquareChaintheTop' : [ SplitSquareThruVariations[13],SplitSquareThruVariations[14],SplitSquareThruVariations[15],SplitSquareThruVariations[16],SplitSquareThruVariations[13],SplitSquareThruVariations[14],SplitSquareThruVariations[15],SplitSquareThruVariations[16],SplitSquareThruVariations[13],SplitSquareThruVariations[14],SplitSquareThruVariations[15],SplitSquareThruVariations[16],SplitSquareThruVariations[13],SplitSquareThruVariations[14],SplitSquareThruVariations[15],SplitSquareThruVariations[16] ],
      'LeftSplitDixieStyletoaWave' : [ SplitSquareThruVariations[17],SplitSquareThruVariations[18],SplitSquareThruVariations[19],SplitSquareThruVariations[20],SplitSquareThruVariations[17],SplitSquareThruVariations[18],SplitSquareThruVariations[19],SplitSquareThruVariations[20],SplitSquareThruVariations[17],SplitSquareThruVariations[18],SplitSquareThruVariations[19],SplitSquareThruVariations[20],SplitSquareThruVariations[17],SplitSquareThruVariations[18],SplitSquareThruVariations[19],SplitSquareThruVariations[20] ],
      'LeftSplitDixieDiamond' : [ SplitSquareThruVariations[21],SplitSquareThruVariations[22],SplitSquareThruVariations[21],SplitSquareThruVariations[22],SplitSquareThruVariations[21],SplitSquareThruVariations[22],SplitSquareThruVariations[21],SplitSquareThruVariations[22] ],
      'LeftSplitDixieSashay' : [ SplitSquareThruVariations[23],SplitSquareThruVariations[24],SplitSquareThruVariations[23],SplitSquareThruVariations[24],SplitSquareThruVariations[23],SplitSquareThruVariations[24],SplitSquareThruVariations[23],SplitSquareThruVariations[24] ],
      'SquareChaintheTop' : [ SquareChainTheTop[0],SquareChainTheTop[1],SquareChainTheTop[2],SquareChainTheTop[3],SquareChainTheTop[4],SquareChainTheTop[5] ],
      'LeftSquareChaintheTop' : [ SquareChainTheTop[6],SquareChainTheTop[7],SquareChainTheTop[8],SquareChainTheTop[9],SquareChainTheTop[10],SquareChainTheTop[11] ],
      'All4CouplesSquareChaintheTop' : [ SquareChainTheTop[12] ],
      'AsCouplesSquareChaintheTop' : [ SquareChainTheTop[13] ],
      'TandemSquareChaintheTop' : [ SquareChainTheTop[14] ],
      'SquaretheBases' : [ SquareTheBases[0] ],
      'EndSqueeze' : [ Squeeze[0],Squeeze[1],Squeeze[0],Squeeze[1],Squeeze[0],Squeeze[1] ],
      'Squeeze' : [ Squeeze[2],Squeeze[3],Squeeze[4],Squeeze[2],Squeeze[3],Squeeze[4],Squeeze[2],Squeeze[3],Squeeze[4] ],
      'CenterTandemSqueeze' : [ Squeeze[5],Squeeze[6],Squeeze[5],Squeeze[6],Squeeze[5],Squeeze[6] ],
      'SqueezetheHourglass' : [ Squeeze[7],Squeeze[8],Squeeze[7],Squeeze[8],Squeeze[7],Squeeze[8] ],
      'SqueezetheGalaxy' : [ Squeeze[9],Squeeze[10],Squeeze[9],Squeeze[10],Squeeze[9],Squeeze[10] ],
      'ThoseFacingStartRightandLeftThru' : [ Start[0] ],
      'BoyStartPasstheOcean' : [ Start[1] ],
      'EndStartLoadtheBoat' : [ Start[2] ],
      'GirlStartTouch14andCross' : [ Start[3] ],
      'GirlStartSpintheTop' : [ Start[4] ],
      'StepandFlip' : [ StepAndFlip[0],StepAndFlip[1],StepAndFlip[2],StepAndFlip[3],StepAndFlip[4],StepAndFlip[5],StepAndFlip[6],StepAndFlip[7],StepAndFlip[8],StepAndFlip[9],StepAndFlip[10],StepAndFlip[11],StepAndFlip[12],StepAndFlip[13],StepAndFlip[14],StepAndFlip[15] ],
      'StepandFlipandRoll' : [ StepAndFlip[16] ],
      'AsCouplesStepandFlip' : [ StepAndFlip[17] ],
      'StretchStepandFlip' : [ StepAndFlip[18] ],
      'TandemStepandFlip' : [ StepAndFlip[19] ],
      'StepandFold' : [ StepAndFold[0],StepAndFold[1],StepAndFold[2],StepAndFold[3],StepAndFold[4],StepAndFold[5],StepAndFold[6],StepAndFold[7],StepAndFold[8],StepAndFold[9],StepAndFold[10],StepAndFold[11],StepAndFold[12],StepAndFold[13],StepAndFold[14],StepAndFold[15] ],
      'All8StepandFold' : [ StepAndFold[16],StepAndFold[17] ],
      'AsCouplesStepandFold' : [ StepAndFold[18] ],
      'ConcentricStepandFold' : [ StepAndFold[19] ],
      'StretchStepandFold' : [ StepAndFold[21] ],
      'TandemStepandFold' : [ StepAndFold[22] ],
      'TripleLineStepandFold' : [ StepAndFold[23] ],
      'StretchBendtheLine' : [ StretchConcept[0] ],
      'StretchCastOff34' : [ StretchConcept[1] ],
      'StretchChaseRight' : [ StretchConcept[2] ],
      'StretchCrossfire' : [ StretchConcept[3] ],
      'StretchCrossTrailThru' : [ StretchConcept[4] ],
      'StretchFlutterwheel' : [ StretchConcept[5],StretchConcept[6] ],
      'StretchHinge' : [ StretchConcept[7] ],
      'StretchLinearCycle' : [ StretchConcept[8] ],
      'StretchPartnerHinge' : [ StretchConcept[9] ],
      'StretchPartnerTrade' : [ StretchConcept[10] ],
      'StretchRecycle' : [ StretchConcept[11],StretchConcept[12] ],
      'StretchReverseFlutterwheel' : [ StretchConcept[13] ],
      'StretchSingleWheel' : [ StretchConcept[15] ],
      'StretchSlide' : [ StretchConcept[16] ],
      'StretchSplitCirculate' : [ StretchConcept[17],StretchConcept[18] ],
      'StretchSplitCounterRotate' : [ StretchConcept[19] ],
      'StretchSplitTransfer' : [ StretchConcept[20],StretchConcept[21] ],
      'StretchSwing' : [ StretchConcept[22] ],
      'StretchTouch' : [ StretchConcept[23] ],
      'StretchTouch14' : [ StretchConcept[24] ],
      'StretchTurnandDeal' : [ StretchConcept[25],StretchConcept[26] ],
      'StretchWheelandDeal' : [ StretchConcept[27] ],
      'StretchVeerRight' : [ StretchConcept[28] ],
      'StretchWheelThru' : [ StretchConcept[29] ],
      'StretchZoom' : [ StretchConcept[30] ],
      'Substitute' : [ Substitute[0],Substitute[1],Substitute[2],Substitute[3] ],
      'SwingandCircle14' : [ SwingAndCircle[0],SwingAndCircle[1],SwingAndCircle[2],SwingAndCircle[3],SwingAndCircle[4],SwingAndCircle[5],SwingAndCircle[6],SwingAndCircle[7],SwingAndCircle[8],SwingAndCircle[9] ],
      'SwingtheFractions' : [ SwingTheFractions[0],SwingTheFractions[1],SwingTheFractions[2] ],
      'LeftSwingtheFractions' : [ SwingTheFractions[3],SwingTheFractions[4],SwingTheFractions[5] ],
      'AnyHandSwingtheFractions' : [ SwingTheFractions[6],SwingTheFractions[7] ],
      'SwitchtheLine' : [ SwitchTheLine[0],SwitchTheLine[1],SwitchTheLine[2],SwitchTheLine[3],SwitchTheLine[4],SwitchTheLine[5],SwitchTheLine[6],SwitchTheLine[7],SwitchTheLine[8],SwitchTheLine[9],SwitchTheLine[10],SwitchTheLine[11],SwitchTheLine[12],SwitchTheLine[13] ],
      'All8SwitchtheLine' : [ SwitchTheLine[14],SwitchTheLine[15],SwitchTheLine[16],SwitchTheLine[17] ],
      'AsCouplesSwitchtheLine' : [ SwitchTheLine[18] ],
      'SwitchtoaDiamond' : [ SwitchToADiamond[0],SwitchToADiamond[1],SwitchToADiamond[2],SwitchToADiamond[3],SwitchToADiamond[4],SwitchToADiamond[5],SwitchToADiamond[6],SwitchToADiamond[7],SwitchToADiamond[8],SwitchToADiamond[9] ],
      'SwitchtoanHourglass' : [ SwitchToAnHourglass[0],SwitchToAnHourglass[1],SwitchToAnHourglass[2] ],
      'SwitchtoanInterlockedDiamond' : [ SwitchToAnInterlockedDiamond[0],SwitchToAnInterlockedDiamond[1],SwitchToAnInterlockedDiamond[2],SwitchToAnInterlockedDiamond[3] ],
      'TallyHo' : [ TallyHo[0],TallyHo[1],TallyHo[2],TallyHo[3],TallyHo[4],TallyHo[5],TallyHo[6],TallyHo[7],TallyHo[8],TallyHo[9],TallyHo[10],TallyHo[11],TallyHo[12],TallyHo[13] ],
      'TandemBendtheLine' : [ TandemConcept[0] ],
      'TandemBoxCirculate' : [ TandemConcept[1] ],
      'TandemBoxTransfer' : [ TandemConcept[2] ],
      'TandemCastOff34' : [ TandemConcept[3] ],
      'TandemCenterRun' : [ TandemConcept[4] ],
      'TandemChaseRight' : [ TandemConcept[5] ],
      'TandemLeftChase' : [ TandemConcept[6] ],
      'TandemCourtesyTurn' : [ TandemConcept[7] ],
      'TandemCrossfire' : [ TandemConcept[8],TandemConcept[9] ],
      'TandemCuttheDiamond' : [ TandemConcept[10],TandemConcept[11] ],
      'TandemDiamondCirculate' : [ TandemConcept[12],TandemConcept[13] ],
      'TandemDixieStyletoaWave' : [ TandemConcept[14] ],
      'TandemFantheTop' : [ TandemConcept[15],TandemConcept[16] ],
      'TandemFliptheDiamond' : [ TandemConcept[17],TandemConcept[18] ],
      'TandemFollowYourNeighbor' : [ TandemConcept[19],TandemConcept[20],TandemConcept[21] ],
      'TandemHinge' : [ TandemConcept[22] ],
      'TandemPartnerHinge' : [ TandemConcept[23] ],
      'TandemPasstheOcean' : [ TandemConcept[24] ],
      'TandemPassThru' : [ TandemConcept[25] ],
      'TandemPeelOff' : [ TandemConcept[26],TandemConcept[27] ],
      'Tandem14Thru' : [ TandemConcept[28] ],
      'TandemRightandLeftThru' : [ TandemConcept[29] ],
      'TandemRightRolltoaWave' : [ TandemConcept[30] ],
      'TandemScootBack' : [ TandemConcept[31] ],
      'TandemSingleWheel' : [ TandemConcept[32] ],
      'TandemSquareChainThru' : [ TandemConcept[33] ],
      'TandemSwingThru' : [ TandemConcept[34] ],
      'TandemSwitchtheWave' : [ TandemConcept[35],TandemConcept[36] ],
      'TandemTouch14' : [ TandemConcept[37] ],
      'TandemWalkandDodge' : [ TandemConcept[38] ],
      'TandemZoom' : [ TandemConcept[39] ],
      '32AceyDeucey' : [ ThreeByTwoAceyDeucey[0],ThreeByTwoAceyDeucey[1],ThreeByTwoAceyDeucey[2],ThreeByTwoAceyDeucey[3],ThreeByTwoAceyDeucey[4] ],
      'Track0' : [ TrackN[0] ],
      'Track1' : [ TrackN[1] ],
      'Track2' : [ TrackN[2] ],
      'Track3' : [ TrackN[3] ],
      'Track4' : [ TrackN[4] ],
      'InsideTriangleCirculate' : [ TriangleFormation[0],TriangleFormation[1],TriangleFormation[2] ],
      'OutsideTriangleCirculate' : [ TriangleFormation[3],TriangleFormation[4],TriangleFormation[5] ],
      'InpointTriangleCirculate' : [ TriangleFormation[6],TriangleFormation[7] ],
      'OutpointTriangleCirculate' : [ TriangleFormation[8],TriangleFormation[9] ],
      'WaveBasedTriangleCirculate' : [ TriangleFormation[10],TriangleFormation[11],TriangleFormation[12],TriangleFormation[13] ],
      'TandemBasedTriangleCirculate' : [ TriangleFormation[14],TriangleFormation[15],TriangleFormation[16],TriangleFormation[17] ],
      'TripleBoxCirculate' : [ TripleBoxConcept[0] ],
      'TripleBoxCounterRotate' : [ TripleBoxConcept[1] ],
      'TripleBoxDixieStyletoaWave' : [ TripleBoxConcept[2] ],
      'TripleBoxFlutterwheel' : [ TripleBoxConcept[3] ],
      'TripleBoxFollowYourNeighborandSpread' : [ TripleBoxConcept[4] ],
      'TripleBoxPassIn' : [ TripleBoxConcept[5] ],
      'TripleBoxPasstheOcean' : [ TripleBoxConcept[6] ],
      'TripleBoxPeelandTrail' : [ TripleBoxConcept[7] ],
      'TripleBox14In' : [ TripleBoxConcept[8] ],
      'TripleBoxRightandLeftThru' : [ TripleBoxConcept[9] ],
      'TripleBoxBoyRun' : [ TripleBoxConcept[10] ],
      'TripleBoxScootBack' : [ TripleBoxConcept[11] ],
      'TripleBoxSquareThru' : [ TripleBoxConcept[12] ],
      'TripleBoxWheelThru' : [ TripleBoxConcept[13] ],
      'TripleColumnPassandRoll' : [ TripleBoxConcept[14] ],
      'TripleLineTurnandDeal' : [ TripleBoxConcept[15] ],
      'TripleWave23Recycle' : [ TripleBoxConcept[16] ],
      'TripleWaveRecycle' : [ TripleBoxConcept[17] ],
      'TripleWaveSwingThru' : [ TripleBoxConcept[18] ],
      'TwisttheLine' : [ TwistTheLine[0],TwistTheLine[1],TwistTheLine[2],TwistTheLine[0],TwistTheLine[1],TwistTheLine[2] ],
      'Twistand' : [ TwistTheLine[3],TwistTheLine[4],TwistTheLine[5],TwistTheLine[6],TwistTheLine[7],TwistTheLine[8],TwistTheLine[9],TwistTheLine[10],TwistTheLine[3],TwistTheLine[4],TwistTheLine[5],TwistTheLine[6],TwistTheLine[7],TwistTheLine[8],TwistTheLine[9],TwistTheLine[10] ],
      'TwistandPassOut' : [ TwistTheLine[11],TwistTheLine[11] ],
      'TwistandSplitSquareThru2' : [ TwistTheLine[12],TwistTheLine[12] ],
      'TwistandSquareThru2' : [ TwistTheLine[13],TwistTheLine[13] ],
      'VerticalTag' : [ VerticalTag[0],VerticalTag[1],VerticalTag[2],VerticalTag[3] ],
      'Vertical14Tag' : [ VerticalTag[4],VerticalTag[5],VerticalTag[6],VerticalTag[7] ],
      'Vertical12Tag' : [ VerticalTag[8],VerticalTag[9],VerticalTag[10],VerticalTag[11] ],
      'Vertical34Tag' : [ VerticalTag[12],VerticalTag[13],VerticalTag[14],VerticalTag[15] ],
      'All8Vertical12Tag' : [ VerticalTag[16] ],
      'Weave' : [ AnythingAndWeave[0],AnythingAndWeave[1],AnythingAndWeave[2],AnythingAndWeave[3],AnythingAndWeave[4],AnythingAndWeave[5],AnythingAndWeave[6],AnythingAndWeave[7] ],
      'AsCouplesWeave' : [ AnythingAndWeave[8] ],
      'All8Weave' : [ AnythingAndWeave[9] ],
      'TandemWeave' : [ AnythingAndWeave[10],AnythingAndWeave[11] ],
      'WheelFanThru' : [ WheelFanThru[0],WheelFanThru[1],WheelFanThru[2] ],
      'LeftWheelFanThru' : [ WheelFanThru[3],WheelFanThru[4],WheelFanThru[5] ],
      'HeadWheelFanThru' : [ WheelFanThru[6] ],
      'SideWheelFanThru' : [ WheelFanThru[7] ],
      'HeadLeftWheelFanThru' : [ WheelFanThru[8] ],
      'SideLeftWheelFanThru' : [ WheelFanThru[9] ],
      'AsCouplesWheelFanThru' : [ WheelFanThru[10] ],
      'All8WheelFanThru' : [ WheelFanThru[11] ],
      'ButterflyWheelFanThru' : [ WheelFanThru[12] ],
      'OWheelFanThru' : [ WheelFanThru[13] ],
      'StretchWheelFanThru' : [ WheelFanThru[14] ],
      'TandemWheelFanThru' : [ WheelFanThru[15] ],
      'TripleBoxWheelFanThru' : [ WheelFanThru[16] ],
      'All8LeftWheelFanThru' : [ WheelFanThru[17] ],
      'AsCouplesLeftWheelFanThru' : [ WheelFanThru[18] ],
      'ButterflyLeftWheelFanThru' : [ WheelFanThru[19] ],
      'OLeftWheelFanThru' : [ WheelFanThru[20] ],
      'StretchLeftWheelFanThru' : [ WheelFanThru[21] ],
      'TandemLeftWheelFanThru' : [ WheelFanThru[22] ],
      'TripleBoxLeftWheelFanThru' : [ WheelFanThru[23] ],
      'BendtheLineWiththeFlow' : [ WithTheFlow[0] ],
      'WheelandDealWiththeFlow' : [ WithTheFlow[1] ],
      'All4CouplesRightandLeftThruWiththeFlow' : [ WithTheFlow[2] ],
      'Zing' : [ Zing[0],Zing[1],Zing[2],Zing[3],Zing[4],Zing[5],Zing[6],Zing[7],Zing[8],Zing[9],Zing[10],Zing[11] ],
      'PointZing' : [ Zing[12] ],
      'All4CouplesZing' : [ Zing[13] ],
      'AsCouplesZing' : [ Zing[14] ],
      'ButterflyZing' : [ Zing[15] ],
      'ConcentricZing' : [ Zing[16] ],
      'OZing' : [ Zing[17] ],
      'StretchZing' : [ Zing[18] ],
      'TandemZing' : [ Zing[19] ],
  };
}
