import '../../animated_call.dart';
import '3_by_1_checkmate_the_column.dart';
import '3_by_1_transfer_the_column.dart';
import '3_by_1_triangle_formation.dart';
import 'swing_along.dart';
import 'alter_and_circulate.dart';
import 'any_tagging_call_your_neighbor.dart';
import 'anything_and_circle.dart';
import 'anything_concept.dart';
import 'cross_the_k.dart';
import 'bounce.dart';
import 'catch.dart';
import 'chain_the_square.dart';
import 'checkpoint.dart';
import 'chisel_thru.dart';
import 'circle_to_a_wave.dart';
import 'counter.dart';
import 'crazy_concept.dart';
import 'criss_cross_the_shadow.dart';
import 'criss_cross_your_neighbor.dart';
import 'cross_and_wheel.dart';
import 'cross_back.dart';
import 'cross_concentric_concept.dart';
import 'invert_the_column.dart';
import 'kick_off.dart';
import 'cross_ramble.dart';
import 'detour.dart';
import 'disconnected_concept.dart';
import 'dodge_anything.dart';
import 'drop_in.dart';
import 'exchange_the_diamond.dart';
import 'fascinate.dart';
import 'file_to_a_line.dart';
import 'funny_concept.dart';
import 'grand_chain_eight.dart';
import 'sock_it_to_me.dart';
import 'hocus_pocus.dart';
import 'rims_trade_anything.dart';
import 'rims_trade_back.dart';
import 'inlet.dart';
import 'interlocked_triangle_formation.dart';
import 'lateral_substitute.dart';
import 'ripple_the_wave.dart';
import 'lines_anything_thru.dart';
import 'little_more.dart';
import 'loop.dart';
import 'offset_concept.dart';
import 'once_removed_concept.dart';
import 'parallelogram_concept.dart';
import 'peel_to_a_diamond.dart';
import 'perk_up.dart';
import 'press.dart';
import 'relocate_the_setup.dart';
import 'reshape_the_triangle.dart';
import 'reverse_cut_the_diamond.dart';
import 'reverse_cut_the_galaxy.dart';
import 'rotate.dart';
import 'split_swap_around.dart';
import 'truck.dart';
import 'rotary.dart';
import 'sets_in_motion.dart';
import 'shazam.dart';
import 'solid_concept.dart';
import 'split_trade_circulate.dart';
import 'stack_the_line.dart';
import 'stagger_concept.dart';
import 'stretched_concept.dart';
import 'swap_the_wave.dart';
import 'tandem_based_triangle.dart';
import 'turn_to_a_line.dart';
import 'unwrap.dart';
import 'vertical_anything.dart';
import 'walk_out_to_a_wave.dart';
import 'wheel_the_ocean.dart';
import 'zip_code.dart';
class CallsIndex {
  static Map<String,List<AnimatedCall>> index = {
      '31CheckmatetheColumn' : [ Q3By1CheckmateTheColumn[0],Q3By1CheckmateTheColumn[1] ],
      '31TransfertheColumn' : [ Q3By1TransferTheColumn[0],Q3By1TransferTheColumn[1] ],
      'Magic31TransfertheColumn' : [ Q3By1TransferTheColumn[2],Q3By1TransferTheColumn[3] ],
      '31TriangleCirculate' : [ Q3By1TriangleFormation[0],Q3By1TriangleFormation[1],Q3By1TriangleFormation[2],Q3By1TriangleFormation[3],Q3By1TriangleFormation[0],Q3By1TriangleFormation[1],Q3By1TriangleFormation[2],Q3By1TriangleFormation[3] ],
      '31InterlockedTriangleCirculate' : [ Q3By1TriangleFormation[4],Q3By1TriangleFormation[5],Q3By1TriangleFormation[4],Q3By1TriangleFormation[5] ],
      'Along' : [ SwingAlong[0],SwingAlong[1],SwingAlong[0],SwingAlong[1] ],
      'SwingAlong' : [ SwingAlong[2],SwingAlong[2] ],
      'AlterandCirculate' : [ AlterAndCirculate[0],AlterAndCirculate[1] ],
      'FlipYourNeighbor' : [ AnyTaggingCallYourNeighbor[0],AnyTaggingCallYourNeighbor[1],AnyTaggingCallYourNeighbor[2],AnyTaggingCallYourNeighbor[3],AnyTaggingCallYourNeighbor[4],AnyTaggingCallYourNeighbor[5],AnyTaggingCallYourNeighbor[0],AnyTaggingCallYourNeighbor[1],AnyTaggingCallYourNeighbor[2],AnyTaggingCallYourNeighbor[3],AnyTaggingCallYourNeighbor[4],AnyTaggingCallYourNeighbor[5],AnyTaggingCallYourNeighbor[0],AnyTaggingCallYourNeighbor[1],AnyTaggingCallYourNeighbor[2],AnyTaggingCallYourNeighbor[3],AnyTaggingCallYourNeighbor[4],AnyTaggingCallYourNeighbor[5],AnyTaggingCallYourNeighbor[0],AnyTaggingCallYourNeighbor[1],AnyTaggingCallYourNeighbor[2],AnyTaggingCallYourNeighbor[3],AnyTaggingCallYourNeighbor[4],AnyTaggingCallYourNeighbor[5] ],
      'FlipYourCrossNeighbor' : [ AnyTaggingCallYourNeighbor[6],AnyTaggingCallYourNeighbor[6],AnyTaggingCallYourNeighbor[6],AnyTaggingCallYourNeighbor[6] ],
      'FlipYourCrissCrossNeighbor' : [ AnyTaggingCallYourNeighbor[7],AnyTaggingCallYourNeighbor[7],AnyTaggingCallYourNeighbor[7],AnyTaggingCallYourNeighbor[7] ],
      'TagYourNeighbor' : [ AnyTaggingCallYourNeighbor[8],AnyTaggingCallYourNeighbor[8],AnyTaggingCallYourNeighbor[8],AnyTaggingCallYourNeighbor[8] ],
      'TagYourCrossNeighbor' : [ AnyTaggingCallYourNeighbor[9],AnyTaggingCallYourNeighbor[9],AnyTaggingCallYourNeighbor[9],AnyTaggingCallYourNeighbor[9] ],
      'TagYourCrissCrossNeighbor' : [ AnyTaggingCallYourNeighbor[10],AnyTaggingCallYourNeighbor[10],AnyTaggingCallYourNeighbor[10],AnyTaggingCallYourNeighbor[10] ],
      'VerticalTagYourNeighbor' : [ AnyTaggingCallYourNeighbor[11],AnyTaggingCallYourNeighbor[11],AnyTaggingCallYourNeighbor[11],AnyTaggingCallYourNeighbor[11] ],
      'VerticalTagYourCrossNeighbor' : [ AnyTaggingCallYourNeighbor[12],AnyTaggingCallYourNeighbor[12],AnyTaggingCallYourNeighbor[12],AnyTaggingCallYourNeighbor[12] ],
      'VerticalTagYourCrissCrossNeighbor' : [ AnyTaggingCallYourNeighbor[13],AnyTaggingCallYourNeighbor[13],AnyTaggingCallYourNeighbor[13],AnyTaggingCallYourNeighbor[13] ],
      'All8RecycleandCircle14' : [ AnythingAndCircle[0] ],
      'DiamondCirculateandCircle14' : [ AnythingAndCircle[1] ],
      'HeadSpintheTopandCircle14' : [ AnythingAndCircle[2] ],
      'InletandCircle14' : [ AnythingAndCircle[3] ],
      'SwitchandCircle14' : [ AnythingAndCircle[4] ],
      'SwitchandCircle12' : [ AnythingAndCircle[5] ],
      'SwingandMixandCircle12' : [ AnythingAndCircle[6] ],
      'SplitCounterCoordinate' : [ AnythingConcept[0] ],
      'SplitCoordinate' : [ AnythingConcept[1] ],
      'CounterMotivate' : [ AnythingConcept[2] ],
      'TradeMotivate' : [ AnythingConcept[3] ],
      'CounterPercolate' : [ AnythingConcept[4] ],
      'SplitPercolate' : [ AnythingConcept[5] ],
      'TradePercolate' : [ AnythingConcept[6] ],
      'CrosstheK' : [ CrossTheK[0],CrossTheK[1],CrossTheK[0],CrossTheK[1] ],
      'theK' : [ CrossTheK[2],CrossTheK[3],CrossTheK[4],CrossTheK[5],CrossTheK[6],CrossTheK[7],CrossTheK[8],CrossTheK[9],CrossTheK[10],CrossTheK[11],CrossTheK[12],CrossTheK[13],CrossTheK[14],CrossTheK[15],CrossTheK[2],CrossTheK[3],CrossTheK[4],CrossTheK[5],CrossTheK[6],CrossTheK[7],CrossTheK[8],CrossTheK[9],CrossTheK[10],CrossTheK[11],CrossTheK[12],CrossTheK[13],CrossTheK[14],CrossTheK[15] ],
      'AsCouplestheK' : [ CrossTheK[16],CrossTheK[16] ],
      'ConcentrictheK' : [ CrossTheK[17],CrossTheK[17] ],
      'CrazytheK' : [ CrossTheK[18],CrossTheK[18] ],
      'CrossConcentrictheK' : [ CrossTheK[19],CrossTheK[19] ],
      'OffsetLinestheK' : [ CrossTheK[20],CrossTheK[20] ],
      '1RemovedtheK' : [ CrossTheK[21],CrossTheK[21] ],
      'TandemtheK' : [ CrossTheK[22],CrossTheK[22] ],
      'CrossTrailThrutheK' : [ CrossTheK[23],CrossTheK[23] ],
      'BouncetheCenter' : [ Bounce[0],Bounce[0] ],
      'BouncetheBoy' : [ Bounce[1],Bounce[1] ],
      'BouncetheGirl' : [ Bounce[2],Bounce[2] ],
      'BouncetheLeaders' : [ Bounce[3],Bounce[3] ],
      'BouncetheTrail' : [ Bounce[4],Bounce[4] ],
      'AsCouplesBouncetheEnd' : [ Bounce[5],Bounce[5] ],
      'ConcentricBouncetheBoy' : [ Bounce[6],Bounce[6] ],
      'CrossConcentricBouncetheBoy' : [ Bounce[7],Bounce[7] ],
      'StretchBouncetheBoy' : [ Bounce[8],Bounce[8] ],
      'TandemBouncetheCenter' : [ Bounce[9],Bounce[9] ],
      'SingleBouncetheBoy' : [ Bounce[10],Bounce[10] ],
      'Catch1' : [ Catch[0] ],
      'Catch2' : [ Catch[1] ],
      'Catch3' : [ Catch[2] ],
      'Catch4' : [ Catch[3] ],
      'ChaintheSquare' : [ ChainTheSquare[0] ],
      'CheckpointAhSoBySwingThru' : [ Checkpoint[0] ],
      'CheckpointTagtheLineBySwingThru' : [ Checkpoint[1] ],
      'CheckpointBoxCirculateByMix' : [ Checkpoint[2] ],
      'CheckpointCounterRotateByTriangleCirculate' : [ Checkpoint[3] ],
      'ChiselThru' : [ ChiselThru[0],ChiselThru[1] ],
      'CircletoaWave' : [ CircleToAWave[0],CircleToAWave[1],CircleToAWave[2] ],
      'Circle12toaWave' : [ CircleToAWave[3] ],
      'All4CouplesCircletoaWave' : [ CircleToAWave[4] ],
      'AsCouplesCircletoaWave' : [ CircleToAWave[5] ],
      'ConcentricCircletoaWave' : [ CircleToAWave[6] ],
      'CrossConcentricCircletoaWave' : [ CircleToAWave[7] ],
      'Counter' : [ Counter[0],Counter[1],Counter[2],Counter[3],Counter[4],Counter[5],Counter[0],Counter[1],Counter[2],Counter[3],Counter[4],Counter[5],Counter[0],Counter[1],Counter[2],Counter[3],Counter[4],Counter[5] ],
      'LeftCounter' : [ Counter[6],Counter[7],Counter[8],Counter[9],Counter[10],Counter[11],Counter[6],Counter[7],Counter[8],Counter[9],Counter[10],Counter[11],Counter[6],Counter[7],Counter[8],Counter[9],Counter[10],Counter[11] ],
      'ScootandCounter' : [ Counter[12],Counter[12],Counter[12] ],
      'LeftScootandCounter' : [ Counter[13],Counter[13],Counter[13] ],
      'CrazyCirculate' : [ CrazyConcept[0],CrazyConcept[0] ],
      'CrazyCirculate3' : [ CrazyConcept[1],CrazyConcept[1] ],
      'CrazyCirculate1223' : [ CrazyConcept[2],CrazyConcept[2] ],
      'CrazyCounterRotate14' : [ CrazyConcept[3],CrazyConcept[3] ],
      'CrazyFlutterwheel' : [ CrazyConcept[4],CrazyConcept[4] ],
      'CrazyMix' : [ CrazyConcept[5],CrazyConcept[5] ],
      'CrazyTrade' : [ CrazyConcept[7],CrazyConcept[7] ],
      'CrazyTriangleCirculate' : [ CrazyConcept[8],CrazyConcept[8] ],
      '12Crazy14Thru' : [ CrazyConcept[9],CrazyConcept[9] ],
      '12CrazyRightandLeftThru' : [ CrazyConcept[10],CrazyConcept[10] ],
      '34CrazyCirculate' : [ CrazyConcept[11],CrazyConcept[11] ],
      'ReverseCrazyReverseFlutterwheel' : [ CrazyConcept[12],CrazyConcept[12] ],
      '12ReverseCrazyTagBack' : [ CrazyConcept[13],CrazyConcept[13] ],
      '12ReverseCrazy23Recycle' : [ CrazyConcept[14],CrazyConcept[14] ],
      '34ReverseCrazyFollowThru' : [ CrazyConcept[15],CrazyConcept[15] ],
      '34ReverseCrazy14Thru' : [ CrazyConcept[16],CrazyConcept[16] ],
      'CrissCrosstheShadow' : [ CrissCrossTheShadow[0],CrissCrossTheShadow[1],CrissCrossTheShadow[2],CrissCrossTheShadow[3],CrissCrossTheShadow[4],CrissCrossTheShadow[5] ],
      'CrissCrossYourNeighbor' : [ CrissCrossYourNeighbor[0],CrissCrossYourNeighbor[1],CrissCrossYourNeighbor[2],CrissCrossYourNeighbor[3],CrissCrossYourNeighbor[4],CrissCrossYourNeighbor[5],CrissCrossYourNeighbor[6],CrissCrossYourNeighbor[7],CrissCrossYourNeighbor[0],CrissCrossYourNeighbor[1],CrissCrossYourNeighbor[2],CrissCrossYourNeighbor[3],CrissCrossYourNeighbor[4],CrissCrossYourNeighbor[5],CrissCrossYourNeighbor[6],CrissCrossYourNeighbor[7] ],
      'All8CrissCrossYourNeighbor' : [ CrissCrossYourNeighbor[8],CrissCrossYourNeighbor[8] ],
      'AsCouplesCrissCrossYourNeighbor' : [ CrissCrossYourNeighbor[9],CrissCrossYourNeighbor[9] ],
      'TandemCrissCrossYourNeighbor' : [ CrissCrossYourNeighbor[10],CrissCrossYourNeighbor[10] ],
      'ConcentricCrissCrossYourNeighbor' : [ CrissCrossYourNeighbor[11],CrissCrossYourNeighbor[11] ],
      'PassandRollYourCrissCrossNeighbor' : [ CrissCrossYourNeighbor[12],CrissCrossYourNeighbor[12] ],
      'LeftPassandRollYourCrissCrossNeighbor' : [ CrissCrossYourNeighbor[13],CrissCrossYourNeighbor[13] ],
      'CrossandWheel' : [ CrossAndWheel[0],CrossAndWheel[1],CrossAndWheel[2],CrossAndWheel[0],CrossAndWheel[1],CrossAndWheel[2],CrossAndWheel[0],CrossAndWheel[1],CrossAndWheel[2],CrossAndWheel[0],CrossAndWheel[1],CrossAndWheel[2],CrossAndWheel[0],CrossAndWheel[1],CrossAndWheel[2],CrossAndWheel[0],CrossAndWheel[1],CrossAndWheel[2],CrossAndWheel[0],CrossAndWheel[1],CrossAndWheel[2] ],
      'CrossTradeandWheel' : [ CrossAndWheel[3],CrossAndWheel[4],CrossAndWheel[5],CrossAndWheel[3],CrossAndWheel[4],CrossAndWheel[5],CrossAndWheel[3],CrossAndWheel[4],CrossAndWheel[5],CrossAndWheel[3],CrossAndWheel[4],CrossAndWheel[5],CrossAndWheel[3],CrossAndWheel[4],CrossAndWheel[5],CrossAndWheel[3],CrossAndWheel[4],CrossAndWheel[5],CrossAndWheel[3],CrossAndWheel[4],CrossAndWheel[5] ],
      'GrandCrossTradeandWheel' : [ CrossAndWheel[6],CrossAndWheel[6],CrossAndWheel[6],CrossAndWheel[6],CrossAndWheel[6],CrossAndWheel[6],CrossAndWheel[6] ],
      'SingleCrossandWheel' : [ CrossAndWheel[7],CrossAndWheel[8],CrossAndWheel[9],CrossAndWheel[10],CrossAndWheel[7],CrossAndWheel[8],CrossAndWheel[9],CrossAndWheel[10],CrossAndWheel[7],CrossAndWheel[8],CrossAndWheel[9],CrossAndWheel[10],CrossAndWheel[7],CrossAndWheel[8],CrossAndWheel[9],CrossAndWheel[10],CrossAndWheel[7],CrossAndWheel[8],CrossAndWheel[9],CrossAndWheel[10],CrossAndWheel[7],CrossAndWheel[8],CrossAndWheel[9],CrossAndWheel[10],CrossAndWheel[7],CrossAndWheel[8],CrossAndWheel[9],CrossAndWheel[10] ],
      'SingleCrossTradeandWheel' : [ CrossAndWheel[11],CrossAndWheel[12],CrossAndWheel[13],CrossAndWheel[14],CrossAndWheel[15],CrossAndWheel[16],CrossAndWheel[17],CrossAndWheel[18],CrossAndWheel[11],CrossAndWheel[12],CrossAndWheel[13],CrossAndWheel[14],CrossAndWheel[15],CrossAndWheel[16],CrossAndWheel[17],CrossAndWheel[18],CrossAndWheel[11],CrossAndWheel[12],CrossAndWheel[13],CrossAndWheel[14],CrossAndWheel[15],CrossAndWheel[16],CrossAndWheel[17],CrossAndWheel[18],CrossAndWheel[11],CrossAndWheel[12],CrossAndWheel[13],CrossAndWheel[14],CrossAndWheel[15],CrossAndWheel[16],CrossAndWheel[17],CrossAndWheel[18],CrossAndWheel[11],CrossAndWheel[12],CrossAndWheel[13],CrossAndWheel[14],CrossAndWheel[15],CrossAndWheel[16],CrossAndWheel[17],CrossAndWheel[18],CrossAndWheel[11],CrossAndWheel[12],CrossAndWheel[13],CrossAndWheel[14],CrossAndWheel[15],CrossAndWheel[16],CrossAndWheel[17],CrossAndWheel[18],CrossAndWheel[11],CrossAndWheel[12],CrossAndWheel[13],CrossAndWheel[14],CrossAndWheel[15],CrossAndWheel[16],CrossAndWheel[17],CrossAndWheel[18] ],
      'GrandSingleCrossandWheel' : [ CrossAndWheel[19],CrossAndWheel[20],CrossAndWheel[21],CrossAndWheel[22],CrossAndWheel[23],CrossAndWheel[24],CrossAndWheel[25],CrossAndWheel[26],CrossAndWheel[27],CrossAndWheel[28],CrossAndWheel[29],CrossAndWheel[30],CrossAndWheel[31],CrossAndWheel[32],CrossAndWheel[33],CrossAndWheel[34],CrossAndWheel[19],CrossAndWheel[20],CrossAndWheel[21],CrossAndWheel[22],CrossAndWheel[23],CrossAndWheel[24],CrossAndWheel[25],CrossAndWheel[26],CrossAndWheel[27],CrossAndWheel[28],CrossAndWheel[29],CrossAndWheel[30],CrossAndWheel[31],CrossAndWheel[32],CrossAndWheel[33],CrossAndWheel[34],CrossAndWheel[19],CrossAndWheel[20],CrossAndWheel[21],CrossAndWheel[22],CrossAndWheel[23],CrossAndWheel[24],CrossAndWheel[25],CrossAndWheel[26],CrossAndWheel[27],CrossAndWheel[28],CrossAndWheel[29],CrossAndWheel[30],CrossAndWheel[31],CrossAndWheel[32],CrossAndWheel[33],CrossAndWheel[34],CrossAndWheel[19],CrossAndWheel[20],CrossAndWheel[21],CrossAndWheel[22],CrossAndWheel[23],CrossAndWheel[24],CrossAndWheel[25],CrossAndWheel[26],CrossAndWheel[27],CrossAndWheel[28],CrossAndWheel[29],CrossAndWheel[30],CrossAndWheel[31],CrossAndWheel[32],CrossAndWheel[33],CrossAndWheel[34],CrossAndWheel[19],CrossAndWheel[20],CrossAndWheel[21],CrossAndWheel[22],CrossAndWheel[23],CrossAndWheel[24],CrossAndWheel[25],CrossAndWheel[26],CrossAndWheel[27],CrossAndWheel[28],CrossAndWheel[29],CrossAndWheel[30],CrossAndWheel[31],CrossAndWheel[32],CrossAndWheel[33],CrossAndWheel[34],CrossAndWheel[19],CrossAndWheel[20],CrossAndWheel[21],CrossAndWheel[22],CrossAndWheel[23],CrossAndWheel[24],CrossAndWheel[25],CrossAndWheel[26],CrossAndWheel[27],CrossAndWheel[28],CrossAndWheel[29],CrossAndWheel[30],CrossAndWheel[31],CrossAndWheel[32],CrossAndWheel[33],CrossAndWheel[34],CrossAndWheel[19],CrossAndWheel[20],CrossAndWheel[21],CrossAndWheel[22],CrossAndWheel[23],CrossAndWheel[24],CrossAndWheel[25],CrossAndWheel[26],CrossAndWheel[27],CrossAndWheel[28],CrossAndWheel[29],CrossAndWheel[30],CrossAndWheel[31],CrossAndWheel[32],CrossAndWheel[33],CrossAndWheel[34] ],
      'GrandSingleCrossTradeandWheel' : [ CrossAndWheel[35],CrossAndWheel[36],CrossAndWheel[37],CrossAndWheel[38],CrossAndWheel[39],CrossAndWheel[40],CrossAndWheel[41],CrossAndWheel[42],CrossAndWheel[43],CrossAndWheel[44],CrossAndWheel[45],CrossAndWheel[46],CrossAndWheel[47],CrossAndWheel[48],CrossAndWheel[49],CrossAndWheel[50],CrossAndWheel[35],CrossAndWheel[36],CrossAndWheel[37],CrossAndWheel[38],CrossAndWheel[39],CrossAndWheel[40],CrossAndWheel[41],CrossAndWheel[42],CrossAndWheel[43],CrossAndWheel[44],CrossAndWheel[45],CrossAndWheel[46],CrossAndWheel[47],CrossAndWheel[48],CrossAndWheel[49],CrossAndWheel[50],CrossAndWheel[35],CrossAndWheel[36],CrossAndWheel[37],CrossAndWheel[38],CrossAndWheel[39],CrossAndWheel[40],CrossAndWheel[41],CrossAndWheel[42],CrossAndWheel[43],CrossAndWheel[44],CrossAndWheel[45],CrossAndWheel[46],CrossAndWheel[47],CrossAndWheel[48],CrossAndWheel[49],CrossAndWheel[50],CrossAndWheel[35],CrossAndWheel[36],CrossAndWheel[37],CrossAndWheel[38],CrossAndWheel[39],CrossAndWheel[40],CrossAndWheel[41],CrossAndWheel[42],CrossAndWheel[43],CrossAndWheel[44],CrossAndWheel[45],CrossAndWheel[46],CrossAndWheel[47],CrossAndWheel[48],CrossAndWheel[49],CrossAndWheel[50],CrossAndWheel[35],CrossAndWheel[36],CrossAndWheel[37],CrossAndWheel[38],CrossAndWheel[39],CrossAndWheel[40],CrossAndWheel[41],CrossAndWheel[42],CrossAndWheel[43],CrossAndWheel[44],CrossAndWheel[45],CrossAndWheel[46],CrossAndWheel[47],CrossAndWheel[48],CrossAndWheel[49],CrossAndWheel[50],CrossAndWheel[35],CrossAndWheel[36],CrossAndWheel[37],CrossAndWheel[38],CrossAndWheel[39],CrossAndWheel[40],CrossAndWheel[41],CrossAndWheel[42],CrossAndWheel[43],CrossAndWheel[44],CrossAndWheel[45],CrossAndWheel[46],CrossAndWheel[47],CrossAndWheel[48],CrossAndWheel[49],CrossAndWheel[50],CrossAndWheel[35],CrossAndWheel[36],CrossAndWheel[37],CrossAndWheel[38],CrossAndWheel[39],CrossAndWheel[40],CrossAndWheel[41],CrossAndWheel[42],CrossAndWheel[43],CrossAndWheel[44],CrossAndWheel[45],CrossAndWheel[46],CrossAndWheel[47],CrossAndWheel[48],CrossAndWheel[49],CrossAndWheel[50] ],
      'CrossBack' : [ CrossBack[0],CrossBack[1],CrossBack[2],CrossBack[3],CrossBack[4],CrossBack[5],CrossBack[0],CrossBack[1],CrossBack[2],CrossBack[3],CrossBack[4],CrossBack[5] ],
      'All8CrossBack' : [ CrossBack[6],CrossBack[6] ],
      'AsCouplesCrossBack' : [ CrossBack[7],CrossBack[7] ],
      'TandemCrossBack' : [ CrossBack[8],CrossBack[8] ],
      'GrandCrossBack' : [ CrossBack[9],CrossBack[10],CrossBack[9],CrossBack[10] ],
      'CrossConcentricCrossfire' : [ CrossConcentricConcept[2] ],
      'CrossConcentricFliptheDiamond' : [ CrossConcentricConcept[3] ],
      'CrossConcentricHinge' : [ CrossConcentricConcept[4] ],
      'CrossConcentricRecycle' : [ CrossConcentricConcept[5] ],
      'CrossConcentricReverseExplode' : [ CrossConcentricConcept[6] ],
      'CrossConcentricStarThru' : [ CrossConcentricConcept[7],CrossConcentricConcept[8],CrossConcentricConcept[9],CrossConcentricConcept[10] ],
      'CrossConcentricStepandFold' : [ CrossConcentricConcept[11] ],
      'CrossConcentricWheelandDeal' : [ CrossConcentricConcept[14] ],
      'InverttheColumn' : [ InvertTheColumn[0],InvertTheColumn[1],InvertTheColumn[0],InvertTheColumn[1] ],
      'ColumnsOf3InverttheColumn' : [ InvertTheColumn[2],InvertTheColumn[2] ],
      'MagicInverttheColumn' : [ InvertTheColumn[3],InvertTheColumn[4],InvertTheColumn[3],InvertTheColumn[4] ],
      'CrossInverttheColumn14' : [ InvertTheColumn[5],InvertTheColumn[6],InvertTheColumn[5],InvertTheColumn[6] ],
      'CrossInverttheColumn12' : [ InvertTheColumn[7],InvertTheColumn[8],InvertTheColumn[7],InvertTheColumn[8] ],
      'CrossInverttheColumn34' : [ InvertTheColumn[9],InvertTheColumn[10],InvertTheColumn[9],InvertTheColumn[10] ],
      'CrossInverttheColumn' : [ InvertTheColumn[11],InvertTheColumn[12],InvertTheColumn[11],InvertTheColumn[12] ],
      'BoyKickOff' : [ KickOff[0],KickOff[1],KickOff[0],KickOff[1] ],
      'CenterCrossKickOff' : [ KickOff[2],KickOff[3],KickOff[4],KickOff[5],KickOff[6],KickOff[7],KickOff[2],KickOff[3],KickOff[4],KickOff[5],KickOff[6],KickOff[7] ],
      'EndCrossKickOff' : [ KickOff[8],KickOff[9],KickOff[10],KickOff[11],KickOff[12],KickOff[13],KickOff[8],KickOff[9],KickOff[10],KickOff[11],KickOff[12],KickOff[13] ],
      'CrossRamble' : [ CrossRamble[0],CrossRamble[1],CrossRamble[2],CrossRamble[0],CrossRamble[1],CrossRamble[2] ],
      '_crossRamblePart1' : [ CrossRamble[3],CrossRamble[4],CrossRamble[3],CrossRamble[4] ],
      'ScootandCrossRamble' : [ CrossRamble[5],CrossRamble[6],CrossRamble[7],CrossRamble[5],CrossRamble[6],CrossRamble[7] ],
      'Detour' : [ Detour[0],Detour[1],Detour[2],Detour[3],Detour[4],Detour[5],Detour[6],Detour[7] ],
      'BoyDisconnectedCrossfire' : [ DisconnectedConcept[0] ],
      'GirlDisconnectedCrossRolltoaWave' : [ DisconnectedConcept[1] ],
      'GirlDisconnectedCrossfire' : [ DisconnectedConcept[2] ],
      'GirlDisconnectedMix' : [ DisconnectedConcept[3] ],
      'GirlDisconnectedSwingThru' : [ DisconnectedConcept[4] ],
      'GirlDisconnectedSwitchtheWave' : [ DisconnectedConcept[5] ],
      'EndDisconnectedChaseRight' : [ DisconnectedConcept[6] ],
      'EndDisconnectedScootBack' : [ DisconnectedConcept[7] ],
      'EndDisconnectedSwap' : [ DisconnectedConcept[8] ],
      'SameSexDisconnectedCrossfire' : [ DisconnectedConcept[9] ],
      'DisconnectedColumnsOf3Circulate' : [ DisconnectedConcept[10] ],
      'DodgeCirculate' : [ DodgeAnything[0] ],
      'DodgeHocusPocus' : [ DodgeAnything[1] ],
      'DodgeLoadtheBoat' : [ DodgeAnything[2] ],
      'DodgeTrade' : [ DodgeAnything[3] ],
      'DropIn' : [ DropIn[0],DropIn[1],DropIn[2],DropIn[3],DropIn[0],DropIn[1],DropIn[2],DropIn[3] ],
      'DropOut' : [ DropIn[4],DropIn[5],DropIn[6],DropIn[7],DropIn[4],DropIn[5],DropIn[6],DropIn[7] ],
      'DropRight' : [ DropIn[8],DropIn[9],DropIn[8],DropIn[9] ],
      'DropLeft' : [ DropIn[10],DropIn[11],DropIn[10],DropIn[11] ],
      'GrandDropIn' : [ DropIn[12],DropIn[12] ],
      'GrandDropOut' : [ DropIn[13],DropIn[13] ],
      'ExchangetheDiamond' : [ ExchangeTheDiamond[0],ExchangeTheDiamond[1],ExchangeTheDiamond[2],ExchangeTheDiamond[3],ExchangeTheDiamond[4],ExchangeTheDiamond[5],ExchangeTheDiamond[6],ExchangeTheDiamond[7] ],
      'Fascinate' : [ Fascinate[0],Fascinate[1] ],
      'FascinatingRecycle' : [ Fascinate[2] ],
      'FascinatingTurnandDeal' : [ Fascinate[3] ],
      'FiletoaLine' : [ FileToALine[0],FileToALine[1],FileToALine[2],FileToALine[3],FileToALine[4],FileToALine[5],FileToALine[6],FileToALine[7],FileToALine[8],FileToALine[9],FileToALine[10],FileToALine[11],FileToALine[12],FileToALine[13],FileToALine[14],FileToALine[15] ],
      'MagicFiletoaLine' : [ FileToALine[16] ],
      'FunnySplitCirculate2' : [ FunnyConcept[0] ],
      'FunnyDiamondCirculate' : [ FunnyConcept[1] ],
      'FunnySlideThru9Times' : [ FunnyConcept[2] ],
      'FunnySquareThru3' : [ FunnyConcept[3] ],
      'GrandChain8' : [ GrandChainEight[0],GrandChainEight[1],GrandChainEight[2],GrandChainEight[3],GrandChainEight[4],GrandChainEight[5] ],
      'SplitGrandChain8' : [ GrandChainEight[6],GrandChainEight[7],GrandChainEight[8],GrandChainEight[9] ],
      'HeadStartSplitGrandChain8' : [ GrandChainEight[10] ],
      'SideStartSplitGrandChain8' : [ GrandChainEight[11] ],
      'SockIttoMe' : [ SockItToMe[0],SockItToMe[1],SockItToMe[2],SockItToMe[3],SockItToMe[4],SockItToMe[5],SockItToMe[6],SockItToMe[7],SockItToMe[8],SockItToMe[9],SockItToMe[10],SockItToMe[11],SockItToMe[12],SockItToMe[13],SockItToMe[14],SockItToMe[15],SockItToMe[0],SockItToMe[1],SockItToMe[2],SockItToMe[3],SockItToMe[4],SockItToMe[5],SockItToMe[6],SockItToMe[7],SockItToMe[8],SockItToMe[9],SockItToMe[10],SockItToMe[11],SockItToMe[12],SockItToMe[13],SockItToMe[14],SockItToMe[15] ],
      'HereComestheJudge' : [ SockItToMe[16],SockItToMe[17],SockItToMe[18],SockItToMe[19],SockItToMe[20],SockItToMe[21],SockItToMe[22],SockItToMe[23],SockItToMe[24],SockItToMe[25],SockItToMe[26],SockItToMe[27],SockItToMe[28],SockItToMe[29],SockItToMe[30],SockItToMe[31],SockItToMe[16],SockItToMe[17],SockItToMe[18],SockItToMe[19],SockItToMe[20],SockItToMe[21],SockItToMe[22],SockItToMe[23],SockItToMe[24],SockItToMe[25],SockItToMe[26],SockItToMe[27],SockItToMe[28],SockItToMe[29],SockItToMe[30],SockItToMe[31] ],
      'HocusPocus' : [ HocusPocus[0],HocusPocus[1],HocusPocus[2],HocusPocus[3],HocusPocus[4],HocusPocus[5],HocusPocus[6] ],
      'RimsTradeChaseRight' : [ RimsTradeAnything[0],RimsTradeAnything[0] ],
      'RimsTradeFollowYourNeighbor' : [ RimsTradeAnything[1],RimsTradeAnything[1] ],
      'RimsTradePasstheOcean' : [ RimsTradeAnything[2],RimsTradeAnything[2] ],
      'RimsTradePassThru' : [ RimsTradeAnything[3],RimsTradeAnything[3] ],
      'HubsTradeZoom' : [ RimsTradeAnything[4],RimsTradeAnything[4] ],
      'RimsTradeBack' : [ RimsTradeBack[0],RimsTradeBack[1],RimsTradeBack[2],RimsTradeBack[0],RimsTradeBack[1],RimsTradeBack[2] ],
      'HubsTradeBack' : [ RimsTradeBack[3],RimsTradeBack[4],RimsTradeBack[5],RimsTradeBack[3],RimsTradeBack[4],RimsTradeBack[5] ],
      'Inlet' : [ Inlet[0],Inlet[1],Inlet[2],Inlet[0],Inlet[1],Inlet[2] ],
      'Outlet' : [ Inlet[3],Inlet[4],Inlet[5],Inlet[6],Inlet[7],Inlet[3],Inlet[4],Inlet[5],Inlet[6],Inlet[7] ],
      'InsideInterlockedTriangleCirculate' : [ InterlockedTriangleFormation[0] ],
      'OutsideInterlockedTriangleCirculate' : [ InterlockedTriangleFormation[1] ],
      'InpointInterlockedTriangleCirculate' : [ InterlockedTriangleFormation[2] ],
      'OutpointInterlockedTriangleCirculate' : [ InterlockedTriangleFormation[3] ],
      'CenterLateralSubstitute' : [ LateralSubstitute[0],LateralSubstitute[1] ],
      'EndRippletheWave' : [ RippleTheWave[0],RippleTheWave[0] ],
      'VeryEndRippletheWave' : [ RippleTheWave[1],RippleTheWave[1] ],
      'VeryEndRipple3' : [ RippleTheWave[2],RippleTheWave[2] ],
      'VeryEndRipple7' : [ RippleTheWave[3],RippleTheWave[3] ],
      'TrailEndLikeaRippleSwingCastOff34andSingleWheel' : [ RippleTheWave[4],RippleTheWave[4] ],
      'OutfacingPointLikeaRippleJaywalkSwingSlipCastOff34' : [ RippleTheWave[5],RippleTheWave[5] ],
      'LinesPasstheOceanThru' : [ LinesAnythingThru[0] ],
      'LittleMore' : [ LittleMore[0],LittleMore[1],LittleMore[2],LittleMore[3],LittleMore[4],LittleMore[5],LittleMore[0],LittleMore[1],LittleMore[2],LittleMore[3],LittleMore[4],LittleMore[5] ],
      'ScootandLittleMore' : [ LittleMore[6],LittleMore[7],LittleMore[6],LittleMore[7] ],
      'EndGirlRightLoop3' : [ Loop[0] ],
      'BoyInLoop2' : [ Loop[1] ],
      'OffsetLinesCirculate' : [ OffsetConcept[0] ],
      'OffsetLinesBendtheLine' : [ OffsetConcept[1] ],
      'OffsetLinesPasstheOcean' : [ OffsetConcept[2] ],
      '1RemovedBoyRun' : [ OnceRemovedConcept[0] ],
      '1RemovedChaseRight' : [ OnceRemovedConcept[1] ],
      '1RemovedCircleBy14By12' : [ OnceRemovedConcept[2] ],
      '1RemovedCirculate' : [ OnceRemovedConcept[3],OnceRemovedConcept[14] ],
      '1RemovedCounterRotate' : [ OnceRemovedConcept[4] ],
      '1RemovedPartnerTrade' : [ OnceRemovedConcept[5] ],
      '1RemovedPasstheOcean' : [ OnceRemovedConcept[6],OnceRemovedConcept[21] ],
      '1RemovedPeelOff' : [ OnceRemovedConcept[7],OnceRemovedConcept[16] ],
      '1RemovedShakedown' : [ OnceRemovedConcept[8] ],
      '1RemovedSingleWheel' : [ OnceRemovedConcept[9] ],
      '1RemovedSquareChainThru' : [ OnceRemovedConcept[10] ],
      '1RemovedSquareThru3toaWave' : [ OnceRemovedConcept[11] ],
      '1RemovedSwap' : [ OnceRemovedConcept[12] ],
      '1RemovedWalkandDodge' : [ OnceRemovedConcept[13],OnceRemovedConcept[19] ],
      '1RemovedHinge' : [ OnceRemovedConcept[15] ],
      '1Removed14Thru' : [ OnceRemovedConcept[17] ],
      '1RemovedTurntoaLine' : [ OnceRemovedConcept[18],OnceRemovedConcept[25] ],
      '1RemovedZoom' : [ OnceRemovedConcept[20] ],
      '1RemovedRightandLeftThru' : [ OnceRemovedConcept[22] ],
      '1RemovedSlideThru' : [ OnceRemovedConcept[23] ],
      '1RemovedTouch14' : [ OnceRemovedConcept[24] ],
      '1RemovedCrossfire' : [ OnceRemovedConcept[26] ],
      '1RemovedReverseExplode' : [ OnceRemovedConcept[27] ],
      '1RemovedSwingThru' : [ OnceRemovedConcept[28] ],
      '1RemovedSwitchtoaDiamond' : [ OnceRemovedConcept[29] ],
      '1RemovedTurnandDeal' : [ OnceRemovedConcept[30],OnceRemovedConcept[34] ],
      '1Removed23Recycle' : [ OnceRemovedConcept[31] ],
      '1RemovedBendtheLine' : [ OnceRemovedConcept[32] ],
      '1RemovedWheelandDeal' : [ OnceRemovedConcept[35] ],
      '1RemovedDiamondCirculate' : [ OnceRemovedConcept[36],OnceRemovedConcept[41] ],
      '1RemovedFliptheDiamond' : [ OnceRemovedConcept[37],OnceRemovedConcept[42] ],
      '1RemovedCuttheDiamond' : [ OnceRemovedConcept[38],OnceRemovedConcept[43] ],
      '1RemovedReverseFliptheDiamond' : [ OnceRemovedConcept[39],OnceRemovedConcept[44] ],
      '1RemovedReverseCuttheDiamond' : [ OnceRemovedConcept[40],OnceRemovedConcept[45] ],
      'ParallelogramAceyDeucey' : [ ParallelogramConcept[0] ],
      'ParallelogramBendtheLine' : [ ParallelogramConcept[1] ],
      'ParallelogramCastOff34' : [ ParallelogramConcept[2] ],
      'ParallelogramInRollCirculate' : [ ParallelogramConcept[3] ],
      'ParallelogramPasstheOcean' : [ ParallelogramConcept[4] ],
      'ParallelogramRecycle' : [ ParallelogramConcept[5] ],
      'ParallelogramScootBack' : [ ParallelogramConcept[6] ],
      'ParallelogramSlideThru' : [ ParallelogramConcept[7] ],
      'ParallelogramSplitCirculate' : [ ParallelogramConcept[8] ],
      'ParallelogramWalkandDodge' : [ ParallelogramConcept[9] ],
      'PeeltoaDiamond' : [ PeelToADiamond[0],PeelToADiamond[1],PeelToADiamond[2],PeelToADiamond[3],PeelToADiamond[4],PeelToADiamond[5],PeelToADiamond[0],PeelToADiamond[1],PeelToADiamond[2],PeelToADiamond[3],PeelToADiamond[4],PeelToADiamond[5] ],
      'All8PeeltoaDiamond' : [ PeelToADiamond[6],PeelToADiamond[6] ],
      'AsCouplesPeeltoaDiamond' : [ PeelToADiamond[7],PeelToADiamond[7] ],
      'ConcentricPeeltoaDiamond' : [ PeelToADiamond[8],PeelToADiamond[8] ],
      'TandemPeeltoaDiamond' : [ PeelToADiamond[9],PeelToADiamond[9] ],
      'TrailtoaDiamond' : [ PeelToADiamond[10],PeelToADiamond[11],PeelToADiamond[12],PeelToADiamond[13],PeelToADiamond[14],PeelToADiamond[15],PeelToADiamond[10],PeelToADiamond[11],PeelToADiamond[12],PeelToADiamond[13],PeelToADiamond[14],PeelToADiamond[15] ],
      'All8TrailtoaDiamond' : [ PeelToADiamond[16],PeelToADiamond[16] ],
      'AsCouplesTrailtoaDiamond' : [ PeelToADiamond[17],PeelToADiamond[17] ],
      'ConcentricTrailtoaDiamond' : [ PeelToADiamond[18],PeelToADiamond[18] ],
      'TandemTrailtoaDiamond' : [ PeelToADiamond[19],PeelToADiamond[19] ],
      'PerkUp' : [ PerkUp[0],PerkUp[1] ],
      'BoyPressRight' : [ Press[0] ],
      'RelocatetheDiamond' : [ RelocateTheSetup[0],RelocateTheSetup[1] ],
      'RelocatetheHourglass' : [ RelocateTheSetup[2],RelocateTheSetup[3] ],
      'RelocatetheSetup' : [ RelocateTheSetup[4],RelocateTheSetup[5],RelocateTheSetup[6] ],
      'ReshapetheOutsideTriangle' : [ ReshapeTheTriangle[0] ],
      'ReverseCuttheDiamond' : [ ReverseCutTheDiamond[0],ReverseCutTheDiamond[1],ReverseCutTheDiamond[2],ReverseCutTheDiamond[3],ReverseCutTheDiamond[4],ReverseCutTheDiamond[5],ReverseCutTheDiamond[6],ReverseCutTheDiamond[7],ReverseCutTheDiamond[8],ReverseCutTheDiamond[9],ReverseCutTheDiamond[10],ReverseCutTheDiamond[11],ReverseCutTheDiamond[12],ReverseCutTheDiamond[13],ReverseCutTheDiamond[14],ReverseCutTheDiamond[15],ReverseCutTheDiamond[16],ReverseCutTheDiamond[17],ReverseCutTheDiamond[18],ReverseCutTheDiamond[19] ],
      'ReverseFliptheDiamond' : [ ReverseCutTheDiamond[20],ReverseCutTheDiamond[21],ReverseCutTheDiamond[22],ReverseCutTheDiamond[23],ReverseCutTheDiamond[24],ReverseCutTheDiamond[25],ReverseCutTheDiamond[26],ReverseCutTheDiamond[27],ReverseCutTheDiamond[28],ReverseCutTheDiamond[29],ReverseCutTheDiamond[30],ReverseCutTheDiamond[31],ReverseCutTheDiamond[32],ReverseCutTheDiamond[33],ReverseCutTheDiamond[34],ReverseCutTheDiamond[35],ReverseCutTheDiamond[36],ReverseCutTheDiamond[37],ReverseCutTheDiamond[38],ReverseCutTheDiamond[39] ],
      'ReverseCuttheGalaxy' : [ ReverseCutTheGalaxy[0],ReverseCutTheGalaxy[1],ReverseCutTheGalaxy[2],ReverseCutTheGalaxy[3],ReverseCutTheGalaxy[4],ReverseCutTheGalaxy[5],ReverseCutTheGalaxy[6],ReverseCutTheGalaxy[7] ],
      'ReverseFliptheGalaxy' : [ ReverseCutTheGalaxy[8],ReverseCutTheGalaxy[9],ReverseCutTheGalaxy[10],ReverseCutTheGalaxy[11],ReverseCutTheGalaxy[12],ReverseCutTheGalaxy[13],ReverseCutTheGalaxy[14],ReverseCutTheGalaxy[15] ],
      'Rotate14' : [ Rotate[0],Rotate[0],Rotate[0],Rotate[0] ],
      'Rotate12' : [ Rotate[1],Rotate[1],Rotate[1],Rotate[1] ],
      'Rotate34' : [ Rotate[2],Rotate[2],Rotate[2],Rotate[2] ],
      'Rotate12andSpread' : [ Rotate[3],Rotate[3],Rotate[3],Rotate[3] ],
      'Rotate12andRoll' : [ Rotate[4],Rotate[4],Rotate[4],Rotate[4] ],
      'All4CouplesRotate12' : [ Rotate[5],Rotate[5],Rotate[5],Rotate[5] ],
      'ReverseRotate34' : [ Rotate[6],Rotate[6],Rotate[6],Rotate[6] ],
      'SingleRotate14' : [ Rotate[7],Rotate[8],Rotate[7],Rotate[8],Rotate[7],Rotate[8],Rotate[7],Rotate[8] ],
      'ReverseSingleRotate14' : [ Rotate[9],Rotate[10],Rotate[9],Rotate[10],Rotate[9],Rotate[10],Rotate[9],Rotate[10] ],
      'SplitSwap' : [ SplitSwapAround[0],SplitSwapAround[1],SplitSwapAround[2],SplitSwapAround[0],SplitSwapAround[1],SplitSwapAround[2] ],
      'HeadSplitSwap' : [ SplitSwapAround[3],SplitSwapAround[3] ],
      'AsCouplesSplitSwap' : [ SplitSwapAround[4],SplitSwapAround[4] ],
      'TandemSplitSwap' : [ SplitSwapAround[5],SplitSwapAround[5] ],
      'ReverseSplitSwap' : [ SplitSwapAround[6],SplitSwapAround[7],SplitSwapAround[8],SplitSwapAround[6],SplitSwapAround[7],SplitSwapAround[8] ],
      'HeadReverseSplitSwap' : [ SplitSwapAround[9],SplitSwapAround[9] ],
      'AsCouplesReverseSplitSwap' : [ SplitSwapAround[10],SplitSwapAround[10] ],
      'TandemReverseSplitSwap' : [ SplitSwapAround[11],SplitSwapAround[11] ],
      'SideReverseSplitSwap' : [ SplitSwapAround[12],SplitSwapAround[12] ],
      'Truck' : [ Truck[0],Truck[1],Truck[0],Truck[1] ],
      'ReverseTruck' : [ Truck[2],Truck[2] ],
      'RotaryExplodetheWave' : [ Rotary[0] ],
      'RotaryMix' : [ Rotary[1] ],
      'RotaryTradetheWave' : [ Rotary[2] ],
      'SetsInMotion' : [ SetsInMotion[0],SetsInMotion[1],SetsInMotion[2],SetsInMotion[3],SetsInMotion[4],SetsInMotion[5],SetsInMotion[6],SetsInMotion[7],SetsInMotion[8],SetsInMotion[9],SetsInMotion[10],SetsInMotion[11],SetsInMotion[12] ],
      'Shazam' : [ Shazam[0],Shazam[1],Shazam[2],Shazam[3],Shazam[4],Shazam[5],Shazam[6] ],
      'CenterShazam' : [ Shazam[7] ],
      'GroupsOf4WorkSolidTouch14' : [ SolidConcept[0] ],
      'CenterWorkSolidAllSwingThru' : [ SolidConcept[1] ],
      'LinesOf3WorkSolidAllDiamondCirculate' : [ SolidConcept[2] ],
      'OutsideTrianglesWorkSolidAllMix' : [ SolidConcept[3] ],
      'TandemBasedTriangleWorkSolidAllFliptheDiamond' : [ SolidConcept[4] ],
      'SplitTradeCirculate' : [ SplitTradeCirculate[0],SplitTradeCirculate[1],SplitTradeCirculate[2],SplitTradeCirculate[3] ],
      'StacktheLine' : [ StackTheLine[0],StackTheLine[1],StackTheLine[2],StackTheLine[3],StackTheLine[4],StackTheLine[5],StackTheLine[6],StackTheLine[7],StackTheLine[8] ],
      'StaggerDoublePassThru' : [ StaggerConcept[0] ],
      'StaggerCirculate' : [ StaggerConcept[1] ],
      'StaggerSplitCirculate' : [ StaggerConcept[2] ],
      'StretchedLineCrossfire' : [ StretchedConcept[0] ],
      'StretchedLineTagtheLine' : [ StretchedConcept[1] ],
      'StretchedLineTurnandDeal' : [ StretchedConcept[2] ],
      'StretchedLineWheelandDeal' : [ StretchedConcept[3] ],
      'StretchedWaveExplodetheWave' : [ StretchedConcept[4] ],
      'StretchedWaveRecycle' : [ StretchedConcept[5] ],
      'SwaptheWave' : [ SwapTheWave[0],SwapTheWave[1],SwapTheWave[2],SwapTheWave[3],SwapTheWave[4],SwapTheWave[5] ],
      'TrianglePeelandTrail' : [ TandemBasedTriangle[0] ],
      'TriangleRecycle' : [ TandemBasedTriangle[1] ],
      'TriangleSwap' : [ TandemBasedTriangle[2] ],
      'TriangleWheelThru' : [ TandemBasedTriangle[3] ],
      'OutsideTriangleCrossYourNeighbor' : [ TandemBasedTriangle[4] ],
      'OutsideTrianglePeelandTrail' : [ TandemBasedTriangle[5] ],
      'OutsideTrianglePeeltheTop' : [ TandemBasedTriangle[6] ],
      'OutsideTrianglePeeltoaDiamond' : [ TandemBasedTriangle[7] ],
      'TurntoaLine' : [ TurnToALine[0],TurnToALine[1],TurnToALine[2],TurnToALine[3],TurnToALine[4],TurnToALine[5],TurnToALine[6],TurnToALine[7],TurnToALine[8],TurnToALine[9],TurnToALine[10],TurnToALine[11],TurnToALine[12],TurnToALine[13],TurnToALine[14],TurnToALine[15],TurnToALine[16],TurnToALine[17],TurnToALine[18],TurnToALine[19],TurnToALine[20],TurnToALine[21],TurnToALine[22],TurnToALine[23],TurnToALine[24],TurnToALine[25],TurnToALine[26],TurnToALine[27] ],
      'TurntoaLineandRoll' : [ TurnToALine[28] ],
      'TurntoaLineandSpread' : [ TurnToALine[29] ],
      'All8TurntoaLine' : [ TurnToALine[30] ],
      'AsCouplesTurntoaLine' : [ TurnToALine[31] ],
      'ButterflyTurntoaLine' : [ TurnToALine[32] ],
      'ConcentricTurntoaLine' : [ TurnToALine[33] ],
      'CrossConcentricTurntoaLine' : [ TurnToALine[34],TurnToALine[35] ],
      'OTurntoaLine' : [ TurnToALine[36] ],
      'StretchTurntoaLine' : [ TurnToALine[37] ],
      'TandemTurntoaLine' : [ TurnToALine[38] ],
      'TurntoaLinetheWindmillRight' : [ TurnToALine[39] ],
      'UnwraptheDiamond' : [ Unwrap[0],Unwrap[1],Unwrap[2],Unwrap[3],Unwrap[4] ],
      'UnwraptheHourglass' : [ Unwrap[5],Unwrap[6] ],
      'UnwraptheButterfly' : [ Unwrap[7],Unwrap[8] ],
      'UnwraptheGalaxy' : [ Unwrap[9],Unwrap[10] ],
      'VerticalDixieStyletoaWave' : [ VerticalAnything[0] ],
      'VerticalGrandChain8' : [ VerticalAnything[1] ],
      'WalkOuttoaWave' : [ WalkOutToAWave[0],WalkOutToAWave[1],WalkOutToAWave[2],WalkOutToAWave[3] ],
      'MagicWalkOuttoaWave' : [ WalkOutToAWave[4],WalkOutToAWave[5] ],
      'WheeltheOcean' : [ WheelTheOcean[0],WheelTheOcean[1],WheelTheOcean[2],WheelTheOcean[3],WheelTheOcean[4],WheelTheOcean[5],WheelTheOcean[0],WheelTheOcean[1],WheelTheOcean[2],WheelTheOcean[3],WheelTheOcean[4],WheelTheOcean[5] ],
      'ReverseWheeltheOcean' : [ WheelTheOcean[6],WheelTheOcean[7],WheelTheOcean[8],WheelTheOcean[9],WheelTheOcean[10],WheelTheOcean[11],WheelTheOcean[6],WheelTheOcean[7],WheelTheOcean[8],WheelTheOcean[9],WheelTheOcean[10],WheelTheOcean[11] ],
      'HeadWheeltheOcean' : [ WheelTheOcean[12],WheelTheOcean[12] ],
      'AsCouplesWheeltheOcean' : [ WheelTheOcean[13],WheelTheOcean[13] ],
      'All8WheeltheOcean' : [ WheelTheOcean[14],WheelTheOcean[14] ],
      'All8ReverseWheeltheOcean' : [ WheelTheOcean[15],WheelTheOcean[15] ],
      'WheeltheSea' : [ WheelTheOcean[16],WheelTheOcean[17],WheelTheOcean[18],WheelTheOcean[19],WheelTheOcean[20],WheelTheOcean[21],WheelTheOcean[16],WheelTheOcean[17],WheelTheOcean[18],WheelTheOcean[19],WheelTheOcean[20],WheelTheOcean[21] ],
      'ReverseWheeltheSea' : [ WheelTheOcean[22],WheelTheOcean[23],WheelTheOcean[24],WheelTheOcean[25],WheelTheOcean[26],WheelTheOcean[27],WheelTheOcean[22],WheelTheOcean[23],WheelTheOcean[24],WheelTheOcean[25],WheelTheOcean[26],WheelTheOcean[27] ],
      'HeadWheeltheSea' : [ WheelTheOcean[28],WheelTheOcean[28] ],
      'AsCouplesWheeltheSea' : [ WheelTheOcean[29],WheelTheOcean[29] ],
      'All8WheeltheSea' : [ WheelTheOcean[30],WheelTheOcean[30] ],
      'All8ReverseWheeltheSea' : [ WheelTheOcean[31],WheelTheOcean[31] ],
      'ZipCode6' : [ ZipCode[0] ],
  };
}
