import '../../animated_call.dart';
import 'allemande.dart';
import 'arm_turns.dart';
import 'turn_back.dart';
import 'bend_the_line.dart';
import 'california_twirl.dart';
import 'ladies_chain.dart';
import 'circle.dart';
import 'circle_to_a_line.dart';
import 'circulate.dart';
import 'courtesy_turn.dart';
import 'dive_thru.dart';
import 'do_paso.dart';
import 'dosado.dart';
import 'double_pass_thru.dart';
import 'face.dart';
import 'first_couple_go.dart';
import 'forward_and_back.dart';
import 'grand_square.dart';
import 'sashay.dart';
import 'lead_right.dart';
import 'pass_thru.dart';
import 'passing_rule.dart';
import 'promenade.dart';
import 'pull_by.dart';
import 'right_and_left_grand.dart';
import 'right_and_left_thru.dart';
import 'star.dart';
import 'same_position_rule.dart';
import 'see_saw.dart';
import 'separate.dart';
import 'split_the_outside_couple.dart';
import 'square_thru.dart';
import 'star_thru.dart';
import 'step_thru.dart';
import 'swing.dart';
import 'veer.dart';
import 'all_around_the_corner.dart';
class CallsIndex {
  static Map<String,List<AnimatedCall>> index = {
      'AllemandeLeft' : [ Allemande[0],Allemande[1],Allemande[2],Allemande[3],Allemande[4],Allemande[5],Allemande[6],Allemande[7],Allemande[8],Allemande[9],Allemande[10],Allemande[11] ],
      'TurnPartnerBytheRight' : [ ArmTurns[0],ArmTurns[0],ArmTurns[0] ],
      'TurnPartnerBytheLeft' : [ ArmTurns[1],ArmTurns[1],ArmTurns[1] ],
      'LeftArmTurn34' : [ ArmTurns[2],ArmTurns[2],ArmTurns[2] ],
      'CenterArmTurn34' : [ ArmTurns[3],ArmTurns[3],ArmTurns[3] ],
      'UTurnBack' : [ TurnBack[0],TurnBack[1],TurnBack[2],TurnBack[3],TurnBack[4],TurnBack[5],TurnBack[6],TurnBack[0],TurnBack[1],TurnBack[2],TurnBack[3],TurnBack[4],TurnBack[5],TurnBack[6] ],
      'BoyTurnBack' : [ TurnBack[7],TurnBack[8],TurnBack[7],TurnBack[8] ],
      'GirlTurnBack' : [ TurnBack[9],TurnBack[10],TurnBack[9],TurnBack[10] ],
      'GirlBacktrack' : [ TurnBack[11],TurnBack[11] ],
      'BendtheLine' : [ BendTheLine[0],BendTheLine[1],BendTheLine[2],BendTheLine[3],BendTheLine[4],BendTheLine[5],BendTheLine[6],BendTheLine[7],BendTheLine[8],BendTheLine[9] ],
      'LineOf8BendtheLine' : [ BendTheLine[10] ],
      'CaliforniaTwirl' : [ CaliforniaTwirl[0],CaliforniaTwirl[1],CaliforniaTwirl[2],CaliforniaTwirl[3] ],
      'GirlChain' : [ LadiesChain[0],LadiesChain[1],LadiesChain[2],LadiesChain[0],LadiesChain[1],LadiesChain[2] ],
      'HeadGirlChain' : [ LadiesChain[3],LadiesChain[3] ],
      'SideGirlChain' : [ LadiesChain[4],LadiesChain[4] ],
      'HeadGirlChainRight' : [ LadiesChain[5],LadiesChain[5] ],
      'SideGirlChainRight' : [ LadiesChain[6],LadiesChain[6] ],
      'HeadGirlChainLeft' : [ LadiesChain[7],LadiesChain[7] ],
      'SideGirlChainLeft' : [ LadiesChain[8],LadiesChain[8] ],
      'EndGirlChainOnaDiagonal' : [ LadiesChain[9],LadiesChain[9] ],
      'CenterGirlChainOnaDiagonal' : [ LadiesChain[10],LadiesChain[10] ],
      'OnaDoubleTrackGirlChain' : [ LadiesChain[11],LadiesChain[11] ],
      '4GirlChain' : [ LadiesChain[12],LadiesChain[13],LadiesChain[12],LadiesChain[13] ],
      '4GirlChain34' : [ LadiesChain[14],LadiesChain[14] ],
      '4GirlChain14' : [ LadiesChain[15],LadiesChain[15] ],
      'ChainDowntheLine' : [ LadiesChain[16],LadiesChain[17],LadiesChain[18],LadiesChain[19],LadiesChain[20],LadiesChain[21],LadiesChain[22],LadiesChain[16],LadiesChain[17],LadiesChain[18],LadiesChain[19],LadiesChain[20],LadiesChain[21],LadiesChain[22] ],
      'CircleLeft' : [ Circle[0] ],
      'CircleLeft18' : [ Circle[1] ],
      'CircleLeft14' : [ Circle[2] ],
      'CircleLeft12' : [ Circle[3] ],
      'CircleLeft34' : [ Circle[4] ],
      'CircleRight' : [ Circle[5] ],
      'CircleRight18' : [ Circle[6] ],
      'CircleRight14' : [ Circle[7] ],
      'CircleRight12' : [ Circle[8] ],
      'CircleRight34' : [ Circle[9] ],
      'Circle4Left14' : [ Circle[10],Circle[11],Circle[12] ],
      'Circle4Right14' : [ Circle[13],Circle[14],Circle[15] ],
      'Circle4Left12' : [ Circle[16],Circle[17],Circle[18] ],
      'Circle4Right12' : [ Circle[19],Circle[20],Circle[21] ],
      'Circle4Left34' : [ Circle[22],Circle[23],Circle[24] ],
      'Circle4Right34' : [ Circle[25],Circle[26],Circle[27] ],
      'SingleCircleLeft14' : [ Circle[28],Circle[29],Circle[30] ],
      'SingleCircleLeft12' : [ Circle[31],Circle[32],Circle[33] ],
      'SingleCircleLeft34' : [ Circle[34],Circle[35],Circle[36] ],
      'SingleCircleRight14' : [ Circle[37],Circle[38],Circle[39] ],
      'SingleCircleRight12' : [ Circle[40],Circle[41],Circle[42] ],
      'SingleCircleRight34' : [ Circle[43],Circle[44],Circle[45] ],
      'CircletoaLine' : [ CircleToALine[0] ],
      'BoxCirculate' : [ Circulate[0],Circulate[1],Circulate[2],Circulate[3],Circulate[4],Circulate[5],Circulate[6],Circulate[7],Circulate[8],Circulate[9],Circulate[0],Circulate[1],Circulate[2],Circulate[3],Circulate[4],Circulate[5],Circulate[6],Circulate[7],Circulate[8],Circulate[9] ],
      'CenterCirculate' : [ Circulate[10],Circulate[11],Circulate[12],Circulate[10],Circulate[11],Circulate[12] ],
      'EndCirculate' : [ Circulate[13],Circulate[14],Circulate[15],Circulate[13],Circulate[14],Circulate[15] ],
      'Circulate' : [ Circulate[16],Circulate[17],Circulate[18],Circulate[19],Circulate[20],Circulate[21],Circulate[22],Circulate[23],Circulate[24],Circulate[25],Circulate[26],Circulate[27],Circulate[28],Circulate[29],Circulate[30],Circulate[31],Circulate[32],Circulate[33],Circulate[45],Circulate[46],Circulate[47],Circulate[48],Circulate[49],Circulate[50],Circulate[51],Circulate[16],Circulate[17],Circulate[18],Circulate[19],Circulate[20],Circulate[21],Circulate[22],Circulate[23],Circulate[24],Circulate[25],Circulate[26],Circulate[27],Circulate[28],Circulate[29],Circulate[30],Circulate[31],Circulate[32],Circulate[33],Circulate[45],Circulate[46],Circulate[47],Circulate[48],Circulate[49],Circulate[50],Circulate[51] ],
      'SplitCirculate' : [ Circulate[34],Circulate[35],Circulate[36],Circulate[37],Circulate[38],Circulate[39],Circulate[40],Circulate[41],Circulate[42],Circulate[43],SamePositionRule[1],Circulate[34],Circulate[35],Circulate[36],Circulate[37],Circulate[38],Circulate[39],Circulate[40],Circulate[41],Circulate[42],Circulate[43] ],
      'SplitCirculate112' : [ Circulate[44],Circulate[44] ],
      'Outer6Circulate' : [ Circulate[52],Circulate[53],Circulate[52],Circulate[53] ],
      'CourtesyTurn' : [ CourtesyTurn[0],CourtesyTurn[1],CourtesyTurn[2] ],
      'CourtesyTurnand14More' : [ CourtesyTurn[3] ],
      'HeadPassThruandCourtesyTurn' : [ CourtesyTurn[4] ],
      'All4GirlMakeaRightHandStarTurnIt1AroundBoyCourtesyTurnYourGirl' : [ CourtesyTurn[5] ],
      'DiveThru' : [ DiveThru[0] ],
      'HeadArchSideDiveThru' : [ DiveThru[1] ],
      'HeadWheelAroundandMakeanArchSideDiveThru' : [ DiveThru[2] ],
      'DoPaso' : [ DoPaso[0] ],
      'DoPasotoanAllemandeThar' : [ DoPaso[1],DoPaso[2] ],
      'Dosado' : [ Dosado[0],Dosado[1],Dosado[2] ],
      'DosadotoaWave' : [ Dosado[3],Dosado[4],Dosado[5] ],
      'DoublePassThru' : [ DoublePassThru[0],DoublePassThru[1],DoublePassThru[2],DoublePassThru[3],DoublePassThru[4] ],
      'LeftDoublePassThru' : [ DoublePassThru[5],DoublePassThru[6],DoublePassThru[7] ],
      'BoyOnaDiagonalDoublePassThru' : [ DoublePassThru[8] ],
      'GirlOnaDiagonalDoublePassThru' : [ DoublePassThru[9] ],
      'OnaDiagonalDoublePassThru' : [ DoublePassThru[10],DoublePassThru[11] ],
      'FaceLeft' : [ Face[0],Face[1] ],
      'FaceRight' : [ Face[2],Face[3] ],
      'FaceIn' : [ Face[4],Face[5],Face[6],Face[7] ],
      'FaceOut' : [ Face[8],Face[9],Face[10],Face[11] ],
      'FirstCoupleGoLeftNextCoupleGoRight' : [ FirstCoupleGo[0] ],
      'FirstCoupleGoRightNextCoupleGoLeft' : [ FirstCoupleGo[1] ],
      'FirstCoupleGoLeftNextCoupleGoLeft' : [ FirstCoupleGo[2] ],
      'FirstCoupleGoRightNextCoupleGoRight' : [ FirstCoupleGo[3] ],
      'ForwardandBack' : [ ForwardAndBack[0],ForwardAndBack[1] ],
      'HeadForwardandBack' : [ ForwardAndBack[2] ],
      'SideForwardandBack' : [ ForwardAndBack[3] ],
      'SideFaceGrandSquare' : [ GrandSquare[0] ],
      'HeadFaceGrandSquare' : [ GrandSquare[1] ],
      'HeadStarThruSideFaceGrandSquare' : [ GrandSquare[2] ],
      'BoyFaceYourPartnerGrandSquare' : [ GrandSquare[3] ],
      'GirlFaceYourPartnerGrandSquare' : [ GrandSquare[4] ],
      'GrandSquare' : [ GrandSquare[5],GrandSquare[6] ],
      '12Sashay' : [ Sashay[0],Sashay[1],Sashay[2],Sashay[0],Sashay[1],Sashay[2],Sashay[0],Sashay[1],Sashay[2] ],
      'Head12Sashay' : [ Sashay[3],Sashay[3],Sashay[3] ],
      'Side12Sashay' : [ Sashay[4],Sashay[4],Sashay[4] ],
      'GirlInBoySashay' : [ Sashay[5],Sashay[6],Sashay[5],Sashay[6],Sashay[5],Sashay[6] ],
      'Rollaway' : [ Sashay[7],Sashay[8],Sashay[9],Sashay[10],Sashay[11],Sashay[7],Sashay[8],Sashay[9],Sashay[10],Sashay[11],Sashay[7],Sashay[8],Sashay[9],Sashay[10],Sashay[11] ],
      'LeadRight' : [ LeadRight[0],LeadRight[1],LeadRight[2] ],
      'LeadLeft' : [ LeadRight[3],LeadRight[4],LeadRight[5] ],
      'HeadLeadRight' : [ LeadRight[6] ],
      'HeadLeadLeft' : [ LeadRight[7] ],
      'SideLeadRight' : [ LeadRight[8] ],
      'SideLeadLeft' : [ LeadRight[9] ],
      'PassThru' : [ PassThru[0],PassThru[1],PassThru[2],PassThru[3] ],
      'HeadPromenade12' : [ Promenade[0],Promenade[0] ],
      'SidePromenade12' : [ Promenade[1],Promenade[1] ],
      'HeadPromenade34' : [ Promenade[2],Promenade[2] ],
      'SidePromenade34' : [ Promenade[3],Promenade[3] ],
      'HeadPromenadeFull' : [ Promenade[4],Promenade[4] ],
      'SidePromenadeFull' : [ Promenade[5],Promenade[5] ],
      'HeadPromenade14' : [ Promenade[6],Promenade[6] ],
      'SidePromenade14' : [ Promenade[7],Promenade[7] ],
      'All4CouplesPromenade14' : [ Promenade[8],Promenade[8] ],
      'All4CouplesPromenade12' : [ Promenade[9],Promenade[9] ],
      'All4CouplesPromenade34' : [ Promenade[10],Promenade[10] ],
      'All4CouplesPromenadeFull' : [ Promenade[11],Promenade[11] ],
      '4BoyPromenade' : [ Promenade[12],Promenade[12] ],
      '4GirlPromenade' : [ Promenade[13],Promenade[13] ],
      'SingleFilePromenade' : [ Promenade[14],Promenade[14] ],
      'StarPromenade' : [ Promenade[15],Promenade[15] ],
      'HeadWrongWayPromenade14' : [ Promenade[16],Promenade[16] ],
      'SideWrongWayPromenade14' : [ Promenade[17],Promenade[17] ],
      'HeadWrongWayPromenade12' : [ Promenade[18],Promenade[18] ],
      'SideWrongWayPromenade12' : [ Promenade[19],Promenade[19] ],
      'HeadWrongWayPromenade34' : [ Promenade[20],Promenade[20] ],
      'SideWrongWayPromenade34' : [ Promenade[21],Promenade[21] ],
      'HeadWrongWayPromenadeFull' : [ Promenade[22],Promenade[22] ],
      'SideWrongWayPromenadeFull' : [ Promenade[23],Promenade[23] ],
      'All4CouplesWrongWayPromenade14' : [ Promenade[24],Promenade[24] ],
      'All4CouplesWrongWayPromenade12' : [ Promenade[25],Promenade[25] ],
      'All4CouplesWrongWayPromenade34' : [ Promenade[26],Promenade[26] ],
      'All4CouplesWrongWayPromenadeFull' : [ Promenade[27],Promenade[27] ],
      'RightPullBy' : [ PullBy[0] ],
      'LeftPullBy' : [ PullBy[1] ],
      'RightandLeftGrand' : [ RightAndLeftGrand[0],RightAndLeftGrand[1],RightAndLeftGrand[2],RightAndLeftGrand[3],RightAndLeftGrand[4],RightAndLeftGrand[5],RightAndLeftGrand[6],RightAndLeftGrand[7],RightAndLeftGrand[8],RightAndLeftGrand[9],RightAndLeftGrand[10],RightAndLeftGrand[11],RightAndLeftGrand[12],RightAndLeftGrand[0],RightAndLeftGrand[1],RightAndLeftGrand[2],RightAndLeftGrand[3],RightAndLeftGrand[4],RightAndLeftGrand[5],RightAndLeftGrand[6],RightAndLeftGrand[7],RightAndLeftGrand[8],RightAndLeftGrand[9],RightAndLeftGrand[10],RightAndLeftGrand[11],RightAndLeftGrand[12],RightAndLeftGrand[0],RightAndLeftGrand[1],RightAndLeftGrand[2],RightAndLeftGrand[3],RightAndLeftGrand[4],RightAndLeftGrand[5],RightAndLeftGrand[6],RightAndLeftGrand[7],RightAndLeftGrand[8],RightAndLeftGrand[9],RightAndLeftGrand[10],RightAndLeftGrand[11],RightAndLeftGrand[12] ],
      'WeavetheRing' : [ RightAndLeftGrand[13],RightAndLeftGrand[13],RightAndLeftGrand[13] ],
      'WrongWayGrand' : [ RightAndLeftGrand[14],RightAndLeftGrand[15],RightAndLeftGrand[16],RightAndLeftGrand[17],RightAndLeftGrand[18],RightAndLeftGrand[19],RightAndLeftGrand[20],RightAndLeftGrand[21],RightAndLeftGrand[22],RightAndLeftGrand[23],RightAndLeftGrand[14],RightAndLeftGrand[15],RightAndLeftGrand[16],RightAndLeftGrand[17],RightAndLeftGrand[18],RightAndLeftGrand[19],RightAndLeftGrand[20],RightAndLeftGrand[21],RightAndLeftGrand[22],RightAndLeftGrand[23],RightAndLeftGrand[14],RightAndLeftGrand[15],RightAndLeftGrand[16],RightAndLeftGrand[17],RightAndLeftGrand[18],RightAndLeftGrand[19],RightAndLeftGrand[20],RightAndLeftGrand[21],RightAndLeftGrand[22],RightAndLeftGrand[23] ],
      'RightandLeftThru' : [ RightAndLeftThru[0],RightAndLeftThru[1],RightAndLeftThru[2],RightAndLeftThru[3],RightAndLeftThru[4],RightAndLeftThru[5] ],
      'HeadRightandLeftThruandBackAway' : [ RightAndLeftThru[6] ],
      'SideRightandLeftThruandBackAway' : [ RightAndLeftThru[7] ],
      'RightandLeftThruand14More' : [ RightAndLeftThru[8],RightAndLeftThru[9] ],
      'CenterRightandLeftThruFullTurn' : [ RightAndLeftThru[10] ],
      'RightHandStar' : [ Star[0],Star[1] ],
      'LeftHandStar' : [ Star[2],Star[3] ],
      'TurntheStar' : [ Star[4],Star[5],Star[6] ],
      'TurntheStars' : [ Star[7],Star[8],Star[9],Star[10] ],
      'HeadRightHandStarAlltheWayAround' : [ Star[11] ],
      'HeadLeftHandStarAlltheWayAround' : [ Star[12] ],
      'HeadSquareThruMakeaRightHandStarWiththeSideHeadCenterLeftHandStarBacktotheSameGirlWithaRightandLeftThru' : [ Star[13] ],
      'RightHandStar14' : [ Star[14] ],
      'RightHandStar12' : [ Star[15] ],
      'RightHandStar34' : [ Star[16] ],
      'RightHandStaraFullTurn' : [ Star[17] ],
      'LeftHandStar14' : [ Star[18] ],
      'LeftHandStar12' : [ Star[19] ],
      'LeftHandStar34' : [ Star[20] ],
      'LeftHandStaraFullTurn' : [ Star[21] ],
      'Circulate112' : [ SamePositionRule[0] ],
      'AllAroundtheCornerSeeSawYourPartner' : [ SeeSaw[0] ],
      'HeadSeparate' : [ Separate[0] ],
      'SideSeparate' : [ Separate[1] ],
      'HeadSeparateandStarThru' : [ Separate[2] ],
      'HeadPassThruSeparateAround1toaLine' : [ Separate[3] ],
      'HeadPassThruSeparateAround1andComeIntotheMiddle' : [ Separate[4] ],
      'HeadPassThruSeparateAround2andComeIntotheMiddle' : [ Separate[5] ],
      'HeadPassThruSeparateAround2toaLine' : [ Separate[6] ],
      'HeadPassThruSeparateAround2MeetYourPartnerandDosado' : [ Separate[7] ],
      'OutsideSeparateandTouch14' : [ Separate[8] ],
      'HeadPasstheOceanandSwingThruOthersSeparateandEverybodyRightandLeftThru' : [ Separate[9] ],
      'Around1toaLine' : [ Separate[10] ],
      'Around2toaLine' : [ Separate[11] ],
      'Around1andComeIntotheMiddle' : [ Separate[12] ],
      'Around2andComeIntotheMiddle' : [ Separate[13] ],
      'CenterSplittheOutsideCouple' : [ SplitTheOutsideCouple[0] ],
      'CenterSplit2' : [ SplitTheOutsideCouple[1] ],
      'CenterSplittheOutsideCoupleSeparateGoAround1toaLine' : [ SplitTheOutsideCouple[2] ],
      'SquareThru2' : [ SquareThru[0],SquareThru[1],SquareThru[2],SquareThru[3],SquareThru[4],SquareThru[5] ],
      'SquareThru3' : [ SquareThru[6],SquareThru[7],SquareThru[8],SquareThru[9],SquareThru[10],SquareThru[11] ],
      'SquareThru' : [ SquareThru[12],SquareThru[13],SquareThru[14],SquareThru[15],SquareThru[16],SquareThru[17] ],
      'LeftSquareThru' : [ SquareThru[18],SquareThru[19],SquareThru[20],SquareThru[21] ],
      'LeftSquareThru312' : [ SquareThru[22],SquareThru[23],SquareThru[24],SquareThru[25] ],
      'LeftSquareThru3' : [ SquareThru[26],SquareThru[27],SquareThru[28],SquareThru[29] ],
      'LeftSquareThru212' : [ SquareThru[30],SquareThru[31],SquareThru[32],SquareThru[33] ],
      'LeftSquareThru2' : [ SquareThru[34],SquareThru[35],SquareThru[36],SquareThru[37] ],
      'LeftSquareThru112' : [ SquareThru[38],SquareThru[39],SquareThru[40],SquareThru[41] ],
      'HeadSquareThru2' : [ SquareThru[42] ],
      'HeadSquareThru3' : [ SquareThru[43] ],
      'HeadSquareThru' : [ SquareThru[44] ],
      'HeadLeftSquareThru' : [ SquareThru[45] ],
      'SideSquareThru2' : [ SquareThru[46] ],
      'SideSquareThru3' : [ SquareThru[47] ],
      'SideSquareThru' : [ SquareThru[48] ],
      'SideLeftSquareThru' : [ SquareThru[49] ],
      'SquareThru112' : [ SquareThru[50],SquareThru[51],SquareThru[52],SquareThru[53],SquareThru[54],SquareThru[55] ],
      'SquareThru212' : [ SquareThru[56],SquareThru[57],SquareThru[58],SquareThru[59],SquareThru[60],SquareThru[61] ],
      'SquareThru312' : [ SquareThru[62],SquareThru[63],SquareThru[64],SquareThru[65],SquareThru[66],SquareThru[67] ],
      'SquareThruon3SpintheTop' : [ SquareThru[68] ],
      'SquareThruon38Chain5' : [ SquareThru[69] ],
      'SquareThruon3BoxtheGnatandRightandLeftGrand' : [ SquareThru[70] ],
      'SquareThruon4LeftSwingThru' : [ SquareThru[71] ],
      'SquareThruon4AllemandeLeft' : [ SquareThru[72] ],
      'SquareThruon3Touch14' : [ SquareThru[73] ],
      'SquareThruon4LeftTouch14' : [ SquareThru[74] ],
      'StarThru' : [ StarThru[0],StarThru[1],StarThru[2],StarThru[3],StarThru[4] ],
      'HeadStarThru' : [ StarThru[5] ],
      'StepThru' : [ StepThru[0],StepThru[1],StepThru[2],StepThru[3],StepThru[4],StepThru[5],StepThru[6],StepThru[7],StepThru[8],StepThru[9],StepThru[10],StepThru[11],StepThru[12],StepThru[13] ],
      'CenterStepThru' : [ StepThru[14] ],
      'SwingYourPartner' : [ Swing[0] ],
      'SwingYourCorner' : [ Swing[1] ],
      'VeerLeft' : [ Veer[0],Veer[1],Veer[2],Veer[3],Veer[4],Veer[5] ],
      'VeerRight' : [ Veer[6],Veer[7],Veer[8],Veer[9],Veer[10],Veer[11] ],
      'WalkAroundtheCorner' : [ AllAroundTheCorner[0],AllAroundTheCorner[1] ],
  };
}
